INFO 2025-01-01 18:58:43,811 autoreload 8604 18444 Watching for file changes with StatReloader
INFO 2025-01-01 18:59:20,496 autoreload 8604 18444 C:\Users\tensa\OneDrive\Escritorio\scs_v1.2\erp_scs\produccion\views.py changed, reloading.
INFO 2025-01-01 18:59:21,540 autoreload 7476 21576 Watching for file changes with StatReloader
INFO 2025-01-01 19:00:13,300 autoreload 7476 21576 C:\Users\tensa\OneDrive\Escritorio\scs_v1.2\erp_scs\produccion\views.py changed, reloading.
INFO 2025-01-01 19:00:14,392 autoreload 4304 22976 Watching for file changes with StatReloader
INFO 2025-01-01 19:00:20,683 autoreload 20572 19220 Watching for file changes with StatReloader
INFO 2025-01-01 19:00:30,697 views 20572 8316 Obteniendo context data
INFO 2025-01-01 19:00:30,698 views 20572 8316 Obteniendo datos iniciales del formulario
INFO 2025-01-01 19:00:30,700 views 20572 8316 GET request - creando formset vacío
INFO 2025-01-01 19:01:37,570 views 20572 8316 Obteniendo datos iniciales del formulario
ERROR 2025-01-01 19:01:37,587 views 20572 8316 Formulario inválido
ERROR 2025-01-01 19:01:37,589 views 20572 8316 Errores en el formulario: <ul class="errorlist"><li>merma_kg<ul class="errorlist"><li>This field is required.</li></ul></li></ul>
INFO 2025-01-01 19:01:37,590 views 20572 8316 Obteniendo context data
INFO 2025-01-01 19:01:37,590 views 20572 8316 Procesando POST - creando formset con datos POST
INFO 2025-01-01 19:03:28,489 views 20572 8316 Obteniendo datos iniciales del formulario
ERROR 2025-01-01 19:03:28,497 views 20572 8316 Formulario inválido
ERROR 2025-01-01 19:03:28,499 views 20572 8316 Errores en el formulario: <ul class="errorlist"><li>merma_kg<ul class="errorlist"><li>This field is required.</li></ul></li></ul>
INFO 2025-01-01 19:03:28,499 views 20572 8316 Obteniendo context data
INFO 2025-01-01 19:03:28,500 views 20572 8316 Procesando POST - creando formset con datos POST
INFO 2025-01-01 19:07:16,756 autoreload 20572 19220 C:\Users\tensa\OneDrive\Escritorio\scs_v1.2\erp_scs\produccion\views.py changed, reloading.
INFO 2025-01-01 19:07:17,864 autoreload 17208 16796 Watching for file changes with StatReloader
INFO 2025-01-01 19:08:15,435 autoreload 17208 16796 C:\Users\tensa\OneDrive\Escritorio\scs_v1.2\erp_scs\produccion\views.py changed, reloading.
INFO 2025-01-01 19:08:16,442 autoreload 23536 9876 Watching for file changes with StatReloader
INFO 2025-01-01 19:12:24,194 autoreload 23536 9876 C:\Users\tensa\OneDrive\Escritorio\scs_v1.2\erp_scs\produccion\views.py changed, reloading.
INFO 2025-01-01 19:12:25,211 autoreload 8824 5644 Watching for file changes with StatReloader
INFO 2025-01-01 19:13:37,673 views 8824 2836 Obteniendo context data
INFO 2025-01-01 19:13:37,673 views 8824 2836 Obteniendo datos iniciales del formulario
INFO 2025-01-01 19:13:37,676 views 8824 2836 GET request - creando formset vacío
INFO 2025-01-01 19:14:04,311 views 8824 2836 Obteniendo datos iniciales del formulario
ERROR 2025-01-01 19:14:04,329 views 8824 2836 Formulario inválido
ERROR 2025-01-01 19:14:04,332 views 8824 2836 Errores en el formulario: <ul class="errorlist"><li>merma_kg<ul class="errorlist"><li>This field is required.</li></ul></li></ul>
INFO 2025-01-01 19:14:04,333 views 8824 2836 Obteniendo context data
INFO 2025-01-01 19:14:04,333 views 8824 2836 Procesando POST - creando formset con datos POST
INFO 2025-01-01 19:23:09,989 autoreload 8824 5644 C:\Users\tensa\OneDrive\Escritorio\scs_v1.2\erp_scs\produccion\views.py changed, reloading.
INFO 2025-01-01 19:23:11,000 autoreload 6680 22052 Watching for file changes with StatReloader
ERROR 2025-01-01 19:24:10,680 views 6680 21752 Formulario inválido
ERROR 2025-01-01 19:24:10,682 views 6680 21752 Errores en el formulario: <ul class="errorlist"><li>merma_kg<ul class="errorlist"><li>This field is required.</li></ul></li></ul>
INFO 2025-01-01 19:24:10,683 views 6680 21752 Procesando POST - creando formset con datos POST
ERROR 2025-01-01 19:24:10,687 views 6680 21752 Errores en el formset: [{'cantidad_producida': ['This field is required.'], 'calidad': ['This field is required.']}, {}]
ERROR 2025-01-01 19:24:19,587 views 6680 21752 Formulario inválido
ERROR 2025-01-01 19:24:19,589 views 6680 21752 Errores en el formulario: <ul class="errorlist"><li>merma_kg<ul class="errorlist"><li>This field is required.</li></ul></li></ul>
INFO 2025-01-01 19:24:19,589 views 6680 21752 Procesando POST - creando formset con datos POST
ERROR 2025-01-01 19:24:19,595 views 6680 21752 Errores en el formset: [{'cantidad_producida': ['This field is required.'], 'calidad': ['This field is required.']}, {}]
ERROR 2025-01-01 19:24:28,964 views 6680 21752 Formulario inválido
ERROR 2025-01-01 19:24:28,966 views 6680 21752 Errores en el formulario: <ul class="errorlist"><li>merma_kg<ul class="errorlist"><li>This field is required.</li></ul></li></ul>
INFO 2025-01-01 19:24:28,966 views 6680 21752 Procesando POST - creando formset con datos POST
ERROR 2025-01-01 19:24:28,971 views 6680 21752 Errores en el formset: [{'cantidad_producida': ['This field is required.'], 'calidad': ['This field is required.']}, {}]
ERROR 2025-01-01 19:24:34,491 views 6680 21752 Formulario inválido
ERROR 2025-01-01 19:24:34,492 views 6680 21752 Errores en el formulario: <ul class="errorlist"><li>merma_kg<ul class="errorlist"><li>This field is required.</li></ul></li></ul>
INFO 2025-01-01 19:24:34,493 views 6680 21752 Procesando POST - creando formset con datos POST
ERROR 2025-01-01 19:24:34,499 views 6680 21752 Errores en el formset: [{'cantidad_producida': ['This field is required.'], 'calidad': ['This field is required.']}, {}]
ERROR 2025-01-01 19:24:46,411 views 6680 21752 Formulario inválido
ERROR 2025-01-01 19:24:46,412 views 6680 21752 Errores en el formulario: <ul class="errorlist"><li>merma_kg<ul class="errorlist"><li>This field is required.</li></ul></li></ul>
INFO 2025-01-01 19:24:46,413 views 6680 21752 Procesando POST - creando formset con datos POST
ERROR 2025-01-01 19:24:46,421 views 6680 21752 Errores en el formset: [{'cantidad_producida': ['This field is required.'], 'calidad': ['This field is required.']}, {}]
INFO 2025-01-01 19:27:00,977 autoreload 6680 22052 C:\Users\tensa\OneDrive\Escritorio\scs_v1.2\erp_scs\produccion\models.py changed, reloading.
INFO 2025-01-01 19:27:02,184 autoreload 21636 16136 Watching for file changes with StatReloader
INFO 2025-01-01 19:28:05,526 autoreload 21636 16136 C:\Users\tensa\OneDrive\Escritorio\scs_v1.2\erp_scs\produccion\forms.py changed, reloading.
INFO 2025-01-01 19:28:06,518 autoreload 22988 19200 Watching for file changes with StatReloader
INFO 2025-01-01 19:28:23,255 views 22988 11328 Iniciando validación del formulario
INFO 2025-01-01 19:28:23,257 views 22988 11328 Procesando POST - creando formset con datos POST
ERROR 2025-01-01 19:28:23,262 views 22988 11328 Errores en el formset: [{'calidad': ['This field is required.']}, {}]
ERROR 2025-01-01 19:28:23,263 views 22988 11328 Errores en formset: [{'calidad': ['This field is required.']}, {}]
ERROR 2025-01-01 19:28:23,263 views 22988 11328 Formulario inválido
ERROR 2025-01-01 19:28:23,272 views 22988 11328 Errores en el formulario: 
INFO 2025-01-01 19:28:23,273 views 22988 11328 Procesando POST - creando formset con datos POST
ERROR 2025-01-01 19:28:23,278 views 22988 11328 Errores en el formset: [{'calidad': ['This field is required.']}, {}]
INFO 2025-01-01 19:28:35,026 views 22988 11328 Iniciando validación del formulario
INFO 2025-01-01 19:28:35,027 views 22988 11328 Procesando POST - creando formset con datos POST
INFO 2025-01-01 19:28:35,054 views 22988 11328 Producción guardada exitosamente con ID: 1
ERROR 2025-01-01 19:28:35,158 log 22988 11328 Internal Server Error: /produccion/lotes/1/
Traceback (most recent call last):
  File "C:\Users\tensa\OneDrive\Escritorio\scs_v1.2\venv\Lib\site-packages\django\template\base.py", line 883, in _resolve_lookup
    current = current[bit]
              ~~~~~~~^^^^^
TypeError: 'ProduccionDiaria' object is not subscriptable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\tensa\OneDrive\Escritorio\scs_v1.2\venv\Lib\site-packages\django\template\base.py", line 893, in _resolve_lookup
    current = getattr(current, bit)
AttributeError: 'ProduccionDiaria' object has no attribute 'supervisor'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\tensa\OneDrive\Escritorio\scs_v1.2\venv\Lib\site-packages\django\template\base.py", line 899, in _resolve_lookup
    current = current[int(bit)]
                      ~~~^^^^^
ValueError: invalid literal for int() with base 10: 'supervisor'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\tensa\OneDrive\Escritorio\scs_v1.2\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\tensa\OneDrive\Escritorio\scs_v1.2\venv\Lib\site-packages\django\core\handlers\base.py", line 220, in _get_response
    response = response.render()
  File "C:\Users\tensa\OneDrive\Escritorio\scs_v1.2\venv\Lib\site-packages\django\template\response.py", line 114, in render
    self.content = self.rendered_content
                   ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\tensa\OneDrive\Escritorio\scs_v1.2\venv\Lib\site-packages\django\template\response.py", line 92, in rendered_content
    return template.render(context, self._request)
           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\tensa\OneDrive\Escritorio\scs_v1.2\venv\Lib\site-packages\django\template\backends\django.py", line 107, in render
    return self.template.render(context)
           ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\tensa\OneDrive\Escritorio\scs_v1.2\venv\Lib\site-packages\django\template\base.py", line 171, in render
    return self._render(context)
           ~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\tensa\OneDrive\Escritorio\scs_v1.2\venv\Lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
           ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\tensa\OneDrive\Escritorio\scs_v1.2\venv\Lib\site-packages\django\template\base.py", line 1008, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\tensa\OneDrive\Escritorio\scs_v1.2\venv\Lib\site-packages\django\template\base.py", line 969, in render_annotated
    return self.render(context)
           ~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\tensa\OneDrive\Escritorio\scs_v1.2\venv\Lib\site-packages\django\template\loader_tags.py", line 159, in render
    return compiled_parent._render(context)
           ~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\tensa\OneDrive\Escritorio\scs_v1.2\venv\Lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
           ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\tensa\OneDrive\Escritorio\scs_v1.2\venv\Lib\site-packages\django\template\base.py", line 1008, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\tensa\OneDrive\Escritorio\scs_v1.2\venv\Lib\site-packages\django\template\base.py", line 969, in render_annotated
    return self.render(context)
           ~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\tensa\OneDrive\Escritorio\scs_v1.2\venv\Lib\site-packages\django\template\loader_tags.py", line 65, in render
    result = block.nodelist.render(context)
  File "C:\Users\tensa\OneDrive\Escritorio\scs_v1.2\venv\Lib\site-packages\django\template\base.py", line 1008, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\tensa\OneDrive\Escritorio\scs_v1.2\venv\Lib\site-packages\django\template\base.py", line 969, in render_annotated
    return self.render(context)
           ~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\tensa\OneDrive\Escritorio\scs_v1.2\venv\Lib\site-packages\django\template\defaulttags.py", line 327, in render
    return nodelist.render(context)
           ~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\tensa\OneDrive\Escritorio\scs_v1.2\venv\Lib\site-packages\django\template\base.py", line 1008, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\tensa\OneDrive\Escritorio\scs_v1.2\venv\Lib\site-packages\django\template\base.py", line 969, in render_annotated
    return self.render(context)
           ~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\tensa\OneDrive\Escritorio\scs_v1.2\venv\Lib\site-packages\django\template\defaulttags.py", line 243, in render
    nodelist.append(node.render_annotated(context))
                    ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\tensa\OneDrive\Escritorio\scs_v1.2\venv\Lib\site-packages\django\template\base.py", line 969, in render_annotated
    return self.render(context)
           ~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\tensa\OneDrive\Escritorio\scs_v1.2\venv\Lib\site-packages\django\template\base.py", line 1067, in render
    output = self.filter_expression.resolve(context)
  File "C:\Users\tensa\OneDrive\Escritorio\scs_v1.2\venv\Lib\site-packages\django\template\base.py", line 739, in resolve
    arg_vals.append(arg.resolve(context))
                    ~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\tensa\OneDrive\Escritorio\scs_v1.2\venv\Lib\site-packages\django\template\base.py", line 850, in resolve
    value = self._resolve_lookup(context)
  File "C:\Users\tensa\OneDrive\Escritorio\scs_v1.2\venv\Lib\site-packages\django\template\base.py", line 906, in _resolve_lookup
    raise VariableDoesNotExist(
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^
    ...<2 lines>...
    )  # missing attribute
    ^
django.template.base.VariableDoesNotExist: Failed lookup for key [supervisor] in <ProduccionDiaria: ProduccionDiaria object (1)>
ERROR 2025-01-01 19:29:13,033 log 22988 11328 Internal Server Error: /produccion/lotes/1/
Traceback (most recent call last):
  File "C:\Users\tensa\OneDrive\Escritorio\scs_v1.2\venv\Lib\site-packages\django\template\base.py", line 883, in _resolve_lookup
    current = current[bit]
              ~~~~~~~^^^^^
TypeError: 'ProduccionDiaria' object is not subscriptable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\tensa\OneDrive\Escritorio\scs_v1.2\venv\Lib\site-packages\django\template\base.py", line 893, in _resolve_lookup
    current = getattr(current, bit)
AttributeError: 'ProduccionDiaria' object has no attribute 'supervisor'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\tensa\OneDrive\Escritorio\scs_v1.2\venv\Lib\site-packages\django\template\base.py", line 899, in _resolve_lookup
    current = current[int(bit)]
                      ~~~^^^^^
ValueError: invalid literal for int() with base 10: 'supervisor'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\tensa\OneDrive\Escritorio\scs_v1.2\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\tensa\OneDrive\Escritorio\scs_v1.2\venv\Lib\site-packages\django\core\handlers\base.py", line 220, in _get_response
    response = response.render()
  File "C:\Users\tensa\OneDrive\Escritorio\scs_v1.2\venv\Lib\site-packages\django\template\response.py", line 114, in render
    self.content = self.rendered_content
                   ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\tensa\OneDrive\Escritorio\scs_v1.2\venv\Lib\site-packages\django\template\response.py", line 92, in rendered_content
    return template.render(context, self._request)
           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\tensa\OneDrive\Escritorio\scs_v1.2\venv\Lib\site-packages\django\template\backends\django.py", line 107, in render
    return self.template.render(context)
           ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\tensa\OneDrive\Escritorio\scs_v1.2\venv\Lib\site-packages\django\template\base.py", line 171, in render
    return self._render(context)
           ~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\tensa\OneDrive\Escritorio\scs_v1.2\venv\Lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
           ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\tensa\OneDrive\Escritorio\scs_v1.2\venv\Lib\site-packages\django\template\base.py", line 1008, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\tensa\OneDrive\Escritorio\scs_v1.2\venv\Lib\site-packages\django\template\base.py", line 969, in render_annotated
    return self.render(context)
           ~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\tensa\OneDrive\Escritorio\scs_v1.2\venv\Lib\site-packages\django\template\loader_tags.py", line 159, in render
    return compiled_parent._render(context)
           ~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\tensa\OneDrive\Escritorio\scs_v1.2\venv\Lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
           ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\tensa\OneDrive\Escritorio\scs_v1.2\venv\Lib\site-packages\django\template\base.py", line 1008, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\tensa\OneDrive\Escritorio\scs_v1.2\venv\Lib\site-packages\django\template\base.py", line 969, in render_annotated
    return self.render(context)
           ~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\tensa\OneDrive\Escritorio\scs_v1.2\venv\Lib\site-packages\django\template\loader_tags.py", line 65, in render
    result = block.nodelist.render(context)
  File "C:\Users\tensa\OneDrive\Escritorio\scs_v1.2\venv\Lib\site-packages\django\template\base.py", line 1008, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\tensa\OneDrive\Escritorio\scs_v1.2\venv\Lib\site-packages\django\template\base.py", line 969, in render_annotated
    return self.render(context)
           ~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\tensa\OneDrive\Escritorio\scs_v1.2\venv\Lib\site-packages\django\template\defaulttags.py", line 327, in render
    return nodelist.render(context)
           ~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\tensa\OneDrive\Escritorio\scs_v1.2\venv\Lib\site-packages\django\template\base.py", line 1008, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\tensa\OneDrive\Escritorio\scs_v1.2\venv\Lib\site-packages\django\template\base.py", line 969, in render_annotated
    return self.render(context)
           ~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\tensa\OneDrive\Escritorio\scs_v1.2\venv\Lib\site-packages\django\template\defaulttags.py", line 243, in render
    nodelist.append(node.render_annotated(context))
                    ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\tensa\OneDrive\Escritorio\scs_v1.2\venv\Lib\site-packages\django\template\base.py", line 969, in render_annotated
    return self.render(context)
           ~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\tensa\OneDrive\Escritorio\scs_v1.2\venv\Lib\site-packages\django\template\base.py", line 1067, in render
    output = self.filter_expression.resolve(context)
  File "C:\Users\tensa\OneDrive\Escritorio\scs_v1.2\venv\Lib\site-packages\django\template\base.py", line 739, in resolve
    arg_vals.append(arg.resolve(context))
                    ~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\tensa\OneDrive\Escritorio\scs_v1.2\venv\Lib\site-packages\django\template\base.py", line 850, in resolve
    value = self._resolve_lookup(context)
  File "C:\Users\tensa\OneDrive\Escritorio\scs_v1.2\venv\Lib\site-packages\django\template\base.py", line 906, in _resolve_lookup
    raise VariableDoesNotExist(
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^
    ...<2 lines>...
    )  # missing attribute
    ^
django.template.base.VariableDoesNotExist: Failed lookup for key [supervisor] in <ProduccionDiaria: ProduccionDiaria object (1)>
INFO 2025-01-01 19:34:19,641 autoreload 23340 7704 Watching for file changes with StatReloader
ERROR 2025-01-01 19:36:38,253 log 23340 18060 Internal Server Error: /produccion/lotes/1/
Traceback (most recent call last):
  File "C:\Users\tensa\OneDrive\Escritorio\scs_v1.2\venv\Lib\site-packages\django\template\base.py", line 883, in _resolve_lookup
    current = current[bit]
              ~~~~~~~^^^^^
TypeError: 'ProduccionDiaria' object is not subscriptable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\tensa\OneDrive\Escritorio\scs_v1.2\venv\Lib\site-packages\django\template\base.py", line 893, in _resolve_lookup
    current = getattr(current, bit)
AttributeError: 'ProduccionDiaria' object has no attribute 'supervisor'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\tensa\OneDrive\Escritorio\scs_v1.2\venv\Lib\site-packages\django\template\base.py", line 899, in _resolve_lookup
    current = current[int(bit)]
                      ~~~^^^^^
ValueError: invalid literal for int() with base 10: 'supervisor'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\tensa\OneDrive\Escritorio\scs_v1.2\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\tensa\OneDrive\Escritorio\scs_v1.2\venv\Lib\site-packages\django\core\handlers\base.py", line 220, in _get_response
    response = response.render()
  File "C:\Users\tensa\OneDrive\Escritorio\scs_v1.2\venv\Lib\site-packages\django\template\response.py", line 114, in render
    self.content = self.rendered_content
                   ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\tensa\OneDrive\Escritorio\scs_v1.2\venv\Lib\site-packages\django\template\response.py", line 92, in rendered_content
    return template.render(context, self._request)
           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\tensa\OneDrive\Escritorio\scs_v1.2\venv\Lib\site-packages\django\template\backends\django.py", line 107, in render
    return self.template.render(context)
           ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\tensa\OneDrive\Escritorio\scs_v1.2\venv\Lib\site-packages\django\template\base.py", line 171, in render
    return self._render(context)
           ~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\tensa\OneDrive\Escritorio\scs_v1.2\venv\Lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
           ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\tensa\OneDrive\Escritorio\scs_v1.2\venv\Lib\site-packages\django\template\base.py", line 1008, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\tensa\OneDrive\Escritorio\scs_v1.2\venv\Lib\site-packages\django\template\base.py", line 969, in render_annotated
    return self.render(context)
           ~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\tensa\OneDrive\Escritorio\scs_v1.2\venv\Lib\site-packages\django\template\loader_tags.py", line 159, in render
    return compiled_parent._render(context)
           ~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\tensa\OneDrive\Escritorio\scs_v1.2\venv\Lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
           ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\tensa\OneDrive\Escritorio\scs_v1.2\venv\Lib\site-packages\django\template\base.py", line 1008, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\tensa\OneDrive\Escritorio\scs_v1.2\venv\Lib\site-packages\django\template\base.py", line 969, in render_annotated
    return self.render(context)
           ~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\tensa\OneDrive\Escritorio\scs_v1.2\venv\Lib\site-packages\django\template\loader_tags.py", line 65, in render
    result = block.nodelist.render(context)
  File "C:\Users\tensa\OneDrive\Escritorio\scs_v1.2\venv\Lib\site-packages\django\template\base.py", line 1008, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\tensa\OneDrive\Escritorio\scs_v1.2\venv\Lib\site-packages\django\template\base.py", line 969, in render_annotated
    return self.render(context)
           ~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\tensa\OneDrive\Escritorio\scs_v1.2\venv\Lib\site-packages\django\template\defaulttags.py", line 327, in render
    return nodelist.render(context)
           ~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\tensa\OneDrive\Escritorio\scs_v1.2\venv\Lib\site-packages\django\template\base.py", line 1008, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\tensa\OneDrive\Escritorio\scs_v1.2\venv\Lib\site-packages\django\template\base.py", line 969, in render_annotated
    return self.render(context)
           ~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\tensa\OneDrive\Escritorio\scs_v1.2\venv\Lib\site-packages\django\template\defaulttags.py", line 243, in render
    nodelist.append(node.render_annotated(context))
                    ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\tensa\OneDrive\Escritorio\scs_v1.2\venv\Lib\site-packages\django\template\base.py", line 969, in render_annotated
    return self.render(context)
           ~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\tensa\OneDrive\Escritorio\scs_v1.2\venv\Lib\site-packages\django\template\base.py", line 1067, in render
    output = self.filter_expression.resolve(context)
  File "C:\Users\tensa\OneDrive\Escritorio\scs_v1.2\venv\Lib\site-packages\django\template\base.py", line 739, in resolve
    arg_vals.append(arg.resolve(context))
                    ~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\tensa\OneDrive\Escritorio\scs_v1.2\venv\Lib\site-packages\django\template\base.py", line 850, in resolve
    value = self._resolve_lookup(context)
  File "C:\Users\tensa\OneDrive\Escritorio\scs_v1.2\venv\Lib\site-packages\django\template\base.py", line 906, in _resolve_lookup
    raise VariableDoesNotExist(
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^
    ...<2 lines>...
    )  # missing attribute
    ^
django.template.base.VariableDoesNotExist: Failed lookup for key [supervisor] in <ProduccionDiaria: ProduccionDiaria object (1)>
ERROR 2025-01-01 19:36:48,476 log 23340 18060 Internal Server Error: /produccion/lotes/1/
Traceback (most recent call last):
  File "C:\Users\tensa\OneDrive\Escritorio\scs_v1.2\venv\Lib\site-packages\django\template\base.py", line 883, in _resolve_lookup
    current = current[bit]
              ~~~~~~~^^^^^
TypeError: 'ProduccionDiaria' object is not subscriptable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\tensa\OneDrive\Escritorio\scs_v1.2\venv\Lib\site-packages\django\template\base.py", line 893, in _resolve_lookup
    current = getattr(current, bit)
AttributeError: 'ProduccionDiaria' object has no attribute 'supervisor'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\tensa\OneDrive\Escritorio\scs_v1.2\venv\Lib\site-packages\django\template\base.py", line 899, in _resolve_lookup
    current = current[int(bit)]
                      ~~~^^^^^
ValueError: invalid literal for int() with base 10: 'supervisor'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\tensa\OneDrive\Escritorio\scs_v1.2\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\tensa\OneDrive\Escritorio\scs_v1.2\venv\Lib\site-packages\django\core\handlers\base.py", line 220, in _get_response
    response = response.render()
  File "C:\Users\tensa\OneDrive\Escritorio\scs_v1.2\venv\Lib\site-packages\django\template\response.py", line 114, in render
    self.content = self.rendered_content
                   ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\tensa\OneDrive\Escritorio\scs_v1.2\venv\Lib\site-packages\django\template\response.py", line 92, in rendered_content
    return template.render(context, self._request)
           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\tensa\OneDrive\Escritorio\scs_v1.2\venv\Lib\site-packages\django\template\backends\django.py", line 107, in render
    return self.template.render(context)
           ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\tensa\OneDrive\Escritorio\scs_v1.2\venv\Lib\site-packages\django\template\base.py", line 171, in render
    return self._render(context)
           ~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\tensa\OneDrive\Escritorio\scs_v1.2\venv\Lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
           ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\tensa\OneDrive\Escritorio\scs_v1.2\venv\Lib\site-packages\django\template\base.py", line 1008, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\tensa\OneDrive\Escritorio\scs_v1.2\venv\Lib\site-packages\django\template\base.py", line 969, in render_annotated
    return self.render(context)
           ~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\tensa\OneDrive\Escritorio\scs_v1.2\venv\Lib\site-packages\django\template\loader_tags.py", line 159, in render
    return compiled_parent._render(context)
           ~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\tensa\OneDrive\Escritorio\scs_v1.2\venv\Lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
           ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\tensa\OneDrive\Escritorio\scs_v1.2\venv\Lib\site-packages\django\template\base.py", line 1008, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\tensa\OneDrive\Escritorio\scs_v1.2\venv\Lib\site-packages\django\template\base.py", line 969, in render_annotated
    return self.render(context)
           ~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\tensa\OneDrive\Escritorio\scs_v1.2\venv\Lib\site-packages\django\template\loader_tags.py", line 65, in render
    result = block.nodelist.render(context)
  File "C:\Users\tensa\OneDrive\Escritorio\scs_v1.2\venv\Lib\site-packages\django\template\base.py", line 1008, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\tensa\OneDrive\Escritorio\scs_v1.2\venv\Lib\site-packages\django\template\base.py", line 969, in render_annotated
    return self.render(context)
           ~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\tensa\OneDrive\Escritorio\scs_v1.2\venv\Lib\site-packages\django\template\defaulttags.py", line 327, in render
    return nodelist.render(context)
           ~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\tensa\OneDrive\Escritorio\scs_v1.2\venv\Lib\site-packages\django\template\base.py", line 1008, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\tensa\OneDrive\Escritorio\scs_v1.2\venv\Lib\site-packages\django\template\base.py", line 969, in render_annotated
    return self.render(context)
           ~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\tensa\OneDrive\Escritorio\scs_v1.2\venv\Lib\site-packages\django\template\defaulttags.py", line 243, in render
    nodelist.append(node.render_annotated(context))
                    ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\tensa\OneDrive\Escritorio\scs_v1.2\venv\Lib\site-packages\django\template\base.py", line 969, in render_annotated
    return self.render(context)
           ~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\tensa\OneDrive\Escritorio\scs_v1.2\venv\Lib\site-packages\django\template\base.py", line 1067, in render
    output = self.filter_expression.resolve(context)
  File "C:\Users\tensa\OneDrive\Escritorio\scs_v1.2\venv\Lib\site-packages\django\template\base.py", line 739, in resolve
    arg_vals.append(arg.resolve(context))
                    ~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\tensa\OneDrive\Escritorio\scs_v1.2\venv\Lib\site-packages\django\template\base.py", line 850, in resolve
    value = self._resolve_lookup(context)
  File "C:\Users\tensa\OneDrive\Escritorio\scs_v1.2\venv\Lib\site-packages\django\template\base.py", line 906, in _resolve_lookup
    raise VariableDoesNotExist(
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^
    ...<2 lines>...
    )  # missing attribute
    ^
django.template.base.VariableDoesNotExist: Failed lookup for key [supervisor] in <ProduccionDiaria: ProduccionDiaria object (1)>
ERROR 2025-01-01 19:50:37,097 views 23340 23228 Formulario inválido
ERROR 2025-01-01 19:50:37,099 views 23340 23228 Errores en el formulario: <ul class="errorlist"><li>__all__<ul class="errorlist nonfield"><li>Produccion diaria with this Lote, Fecha and Trabajador already exists.</li></ul></li></ul>
INFO 2025-01-01 19:50:37,101 views 23340 23228 Procesando POST - creando formset con datos POST
ERROR 2025-01-01 19:51:43,167 views 23340 23228 Formulario inválido
ERROR 2025-01-01 19:51:43,168 views 23340 23228 Errores en el formulario: <ul class="errorlist"><li>__all__<ul class="errorlist nonfield"><li>Produccion diaria with this Lote, Fecha and Trabajador already exists.</li></ul></li></ul>
INFO 2025-01-01 19:51:43,169 views 23340 23228 Procesando POST - creando formset con datos POST
INFO 2025-01-01 19:55:58,877 autoreload 23340 7704 C:\Users\tensa\OneDrive\Escritorio\scs_v1.2\erp_scs\produccion\models.py changed, reloading.
INFO 2025-01-01 19:56:00,103 autoreload 15652 22140 Watching for file changes with StatReloader
INFO 2025-01-01 19:57:01,313 autoreload 15608 14164 Watching for file changes with StatReloader
INFO 2025-01-01 19:57:33,124 views 15608 13168 Iniciando validación del formulario
INFO 2025-01-01 19:57:33,125 views 15608 13168 Procesando POST - creando formset con datos POST
INFO 2025-01-01 19:57:33,144 views 15608 13168 Producción guardada exitosamente con ID: 2
INFO 2025-01-01 20:31:46,831 autoreload 15608 14164 C:\Users\tensa\OneDrive\Escritorio\scs_v1.2\erp_scs\produccion\models.py changed, reloading.
INFO 2025-01-01 20:31:48,038 autoreload 9316 8596 Watching for file changes with StatReloader
INFO 2025-01-01 20:34:00,292 autoreload 9316 8596 C:\Users\tensa\OneDrive\Escritorio\scs_v1.2\erp_scs\produccion\models.py changed, reloading.
INFO 2025-01-01 20:34:01,316 autoreload 256 22140 Watching for file changes with StatReloader
INFO 2025-01-01 20:37:50,355 autoreload 256 22140 C:\Users\tensa\OneDrive\Escritorio\scs_v1.2\erp_scs\produccion\forms.py changed, reloading.
INFO 2025-01-01 20:37:51,520 autoreload 404 14340 Watching for file changes with StatReloader
INFO 2025-01-01 20:39:26,107 autoreload 404 14340 C:\Users\tensa\OneDrive\Escritorio\scs_v1.2\erp_scs\produccion\forms.py changed, reloading.
INFO 2025-01-01 20:39:27,116 autoreload 9372 4464 Watching for file changes with StatReloader
INFO 2025-01-01 20:40:59,192 autoreload 9372 4464 C:\Users\tensa\OneDrive\Escritorio\scs_v1.2\erp_scs\produccion\views.py changed, reloading.
INFO 2025-01-01 20:41:00,186 autoreload 11532 7768 Watching for file changes with StatReloader
INFO 2025-01-01 20:42:38,956 autoreload 11532 7768 C:\Users\tensa\OneDrive\Escritorio\scs_v1.2\erp_scs\produccion\views.py changed, reloading.
INFO 2025-01-01 20:42:39,948 autoreload 20032 17148 Watching for file changes with StatReloader
ERROR 2025-01-01 20:58:24,539 log 20032 6132 Internal Server Error: /produccion/produccion/crear/
Traceback (most recent call last):
  File "C:\Users\tensa\OneDrive\Escritorio\scs_v1.2\venv\Lib\site-packages\django\db\backends\utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
           ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "C:\Users\tensa\OneDrive\Escritorio\scs_v1.2\venv\Lib\site-packages\django\db\backends\sqlite3\base.py", line 354, in execute
    return super().execute(query, params)
           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
sqlite3.OperationalError: table produccion_producciondiaria has no column named estado

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\tensa\OneDrive\Escritorio\scs_v1.2\erp_scs\produccion\views.py", line 150, in form_valid
    self.object.save()
    ~~~~~~~~~~~~~~~~^^
  File "C:\Users\tensa\OneDrive\Escritorio\scs_v1.2\venv\Lib\site-packages\django\db\models\base.py", line 892, in save
    self.save_base(
    ~~~~~~~~~~~~~~^
        using=using,
        ^^^^^^^^^^^^
    ...<2 lines>...
        update_fields=update_fields,
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "C:\Users\tensa\OneDrive\Escritorio\scs_v1.2\venv\Lib\site-packages\django\db\models\base.py", line 998, in save_base
    updated = self._save_table(
        raw,
    ...<4 lines>...
        update_fields,
    )
  File "C:\Users\tensa\OneDrive\Escritorio\scs_v1.2\venv\Lib\site-packages\django\db\models\base.py", line 1161, in _save_table
    results = self._do_insert(
        cls._base_manager, using, fields, returning_fields, raw
    )
  File "C:\Users\tensa\OneDrive\Escritorio\scs_v1.2\venv\Lib\site-packages\django\db\models\base.py", line 1202, in _do_insert
    return manager._insert(
           ~~~~~~~~~~~~~~~^
        [self],
        ^^^^^^^
    ...<3 lines>...
        raw=raw,
        ^^^^^^^^
    )
    ^
  File "C:\Users\tensa\OneDrive\Escritorio\scs_v1.2\venv\Lib\site-packages\django\db\models\manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^
  File "C:\Users\tensa\OneDrive\Escritorio\scs_v1.2\venv\Lib\site-packages\django\db\models\query.py", line 1847, in _insert
    return query.get_compiler(using=using).execute_sql(returning_fields)
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^
  File "C:\Users\tensa\OneDrive\Escritorio\scs_v1.2\venv\Lib\site-packages\django\db\models\sql\compiler.py", line 1836, in execute_sql
    cursor.execute(sql, params)
    ~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "C:\Users\tensa\OneDrive\Escritorio\scs_v1.2\venv\Lib\site-packages\django\db\backends\utils.py", line 122, in execute
    return super().execute(sql, params)
           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "C:\Users\tensa\OneDrive\Escritorio\scs_v1.2\venv\Lib\site-packages\django\db\backends\utils.py", line 79, in execute
    return self._execute_with_wrappers(
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~^
        sql, params, many=False, executor=self._execute
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "C:\Users\tensa\OneDrive\Escritorio\scs_v1.2\venv\Lib\site-packages\django\db\backends\utils.py", line 92, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "C:\Users\tensa\OneDrive\Escritorio\scs_v1.2\venv\Lib\site-packages\django\db\backends\utils.py", line 100, in _execute
    with self.db.wrap_database_errors:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\tensa\OneDrive\Escritorio\scs_v1.2\venv\Lib\site-packages\django\db\utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "C:\Users\tensa\OneDrive\Escritorio\scs_v1.2\venv\Lib\site-packages\django\db\backends\utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
           ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "C:\Users\tensa\OneDrive\Escritorio\scs_v1.2\venv\Lib\site-packages\django\db\backends\sqlite3\base.py", line 354, in execute
    return super().execute(query, params)
           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
django.db.utils.OperationalError: table produccion_producciondiaria has no column named estado

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\tensa\OneDrive\Escritorio\scs_v1.2\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\tensa\OneDrive\Escritorio\scs_v1.2\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\tensa\OneDrive\Escritorio\scs_v1.2\venv\Lib\site-packages\django\views\generic\base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
           ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\tensa\OneDrive\Escritorio\scs_v1.2\venv\Lib\site-packages\django\contrib\auth\mixins.py", line 73, in dispatch
    return super().dispatch(request, *args, **kwargs)
           ~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\tensa\OneDrive\Escritorio\scs_v1.2\venv\Lib\site-packages\django\views\generic\base.py", line 143, in dispatch
    return handler(request, *args, **kwargs)
  File "C:\Users\tensa\OneDrive\Escritorio\scs_v1.2\venv\Lib\site-packages\django\views\generic\edit.py", line 182, in post
    return super().post(request, *args, **kwargs)
           ~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\tensa\OneDrive\Escritorio\scs_v1.2\venv\Lib\site-packages\django\views\generic\edit.py", line 151, in post
    return self.form_valid(form)
           ~~~~~~~~~~~~~~~^^^^^^
  File "C:\Users\tensa\OneDrive\Escritorio\scs_v1.2\erp_scs\produccion\views.py", line 176, in form_valid
    transaction.set_rollback(True)
    ~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^
  File "C:\Users\tensa\OneDrive\Escritorio\scs_v1.2\venv\Lib\site-packages\django\db\transaction.py", line 97, in set_rollback
    return get_connection(using).set_rollback(rollback)
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^
  File "C:\Users\tensa\OneDrive\Escritorio\scs_v1.2\venv\Lib\site-packages\django\db\backends\base\base.py", line 507, in set_rollback
    raise TransactionManagementError(
        "The rollback flag doesn't work outside of an 'atomic' block."
    )
django.db.transaction.TransactionManagementError: The rollback flag doesn't work outside of an 'atomic' block.
INFO 2025-01-01 21:11:02,027 autoreload 20032 17148 C:\Users\tensa\OneDrive\Escritorio\scs_v1.2\erp_scs\produccion\views.py changed, reloading.
INFO 2025-01-01 21:11:03,189 autoreload 2268 10576 Watching for file changes with StatReloader
ERROR 2025-01-01 21:11:12,986 views 2268 11820 Error al procesar la producción
Traceback (most recent call last):
  File "C:\Users\tensa\OneDrive\Escritorio\scs_v1.2\venv\Lib\site-packages\django\db\backends\utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
           ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "C:\Users\tensa\OneDrive\Escritorio\scs_v1.2\venv\Lib\site-packages\django\db\backends\sqlite3\base.py", line 354, in execute
    return super().execute(query, params)
           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
sqlite3.OperationalError: table produccion_producciondiaria has no column named estado

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\tensa\OneDrive\Escritorio\scs_v1.2\erp_scs\produccion\views.py", line 151, in form_valid
    self.object.save()
    ~~~~~~~~~~~~~~~~^^
  File "C:\Users\tensa\OneDrive\Escritorio\scs_v1.2\venv\Lib\site-packages\django\db\models\base.py", line 892, in save
    self.save_base(
    ~~~~~~~~~~~~~~^
        using=using,
        ^^^^^^^^^^^^
    ...<2 lines>...
        update_fields=update_fields,
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "C:\Users\tensa\OneDrive\Escritorio\scs_v1.2\venv\Lib\site-packages\django\db\models\base.py", line 998, in save_base
    updated = self._save_table(
        raw,
    ...<4 lines>...
        update_fields,
    )
  File "C:\Users\tensa\OneDrive\Escritorio\scs_v1.2\venv\Lib\site-packages\django\db\models\base.py", line 1161, in _save_table
    results = self._do_insert(
        cls._base_manager, using, fields, returning_fields, raw
    )
  File "C:\Users\tensa\OneDrive\Escritorio\scs_v1.2\venv\Lib\site-packages\django\db\models\base.py", line 1202, in _do_insert
    return manager._insert(
           ~~~~~~~~~~~~~~~^
        [self],
        ^^^^^^^
    ...<3 lines>...
        raw=raw,
        ^^^^^^^^
    )
    ^
  File "C:\Users\tensa\OneDrive\Escritorio\scs_v1.2\venv\Lib\site-packages\django\db\models\manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^
  File "C:\Users\tensa\OneDrive\Escritorio\scs_v1.2\venv\Lib\site-packages\django\db\models\query.py", line 1847, in _insert
    return query.get_compiler(using=using).execute_sql(returning_fields)
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^
  File "C:\Users\tensa\OneDrive\Escritorio\scs_v1.2\venv\Lib\site-packages\django\db\models\sql\compiler.py", line 1836, in execute_sql
    cursor.execute(sql, params)
    ~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "C:\Users\tensa\OneDrive\Escritorio\scs_v1.2\venv\Lib\site-packages\django\db\backends\utils.py", line 122, in execute
    return super().execute(sql, params)
           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "C:\Users\tensa\OneDrive\Escritorio\scs_v1.2\venv\Lib\site-packages\django\db\backends\utils.py", line 79, in execute
    return self._execute_with_wrappers(
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~^
        sql, params, many=False, executor=self._execute
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "C:\Users\tensa\OneDrive\Escritorio\scs_v1.2\venv\Lib\site-packages\django\db\backends\utils.py", line 92, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "C:\Users\tensa\OneDrive\Escritorio\scs_v1.2\venv\Lib\site-packages\django\db\backends\utils.py", line 100, in _execute
    with self.db.wrap_database_errors:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\tensa\OneDrive\Escritorio\scs_v1.2\venv\Lib\site-packages\django\db\utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "C:\Users\tensa\OneDrive\Escritorio\scs_v1.2\venv\Lib\site-packages\django\db\backends\utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
           ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "C:\Users\tensa\OneDrive\Escritorio\scs_v1.2\venv\Lib\site-packages\django\db\backends\sqlite3\base.py", line 354, in execute
    return super().execute(query, params)
           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
django.db.utils.OperationalError: table produccion_producciondiaria has no column named estado
ERROR 2025-01-01 21:11:20,277 views 2268 11820 Error al procesar la producción
Traceback (most recent call last):
  File "C:\Users\tensa\OneDrive\Escritorio\scs_v1.2\venv\Lib\site-packages\django\db\backends\utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
           ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "C:\Users\tensa\OneDrive\Escritorio\scs_v1.2\venv\Lib\site-packages\django\db\backends\sqlite3\base.py", line 354, in execute
    return super().execute(query, params)
           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
sqlite3.OperationalError: table produccion_producciondiaria has no column named estado

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\tensa\OneDrive\Escritorio\scs_v1.2\erp_scs\produccion\views.py", line 151, in form_valid
    self.object.save()
    ~~~~~~~~~~~~~~~~^^
  File "C:\Users\tensa\OneDrive\Escritorio\scs_v1.2\venv\Lib\site-packages\django\db\models\base.py", line 892, in save
    self.save_base(
    ~~~~~~~~~~~~~~^
        using=using,
        ^^^^^^^^^^^^
    ...<2 lines>...
        update_fields=update_fields,
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "C:\Users\tensa\OneDrive\Escritorio\scs_v1.2\venv\Lib\site-packages\django\db\models\base.py", line 998, in save_base
    updated = self._save_table(
        raw,
    ...<4 lines>...
        update_fields,
    )
  File "C:\Users\tensa\OneDrive\Escritorio\scs_v1.2\venv\Lib\site-packages\django\db\models\base.py", line 1161, in _save_table
    results = self._do_insert(
        cls._base_manager, using, fields, returning_fields, raw
    )
  File "C:\Users\tensa\OneDrive\Escritorio\scs_v1.2\venv\Lib\site-packages\django\db\models\base.py", line 1202, in _do_insert
    return manager._insert(
           ~~~~~~~~~~~~~~~^
        [self],
        ^^^^^^^
    ...<3 lines>...
        raw=raw,
        ^^^^^^^^
    )
    ^
  File "C:\Users\tensa\OneDrive\Escritorio\scs_v1.2\venv\Lib\site-packages\django\db\models\manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^
  File "C:\Users\tensa\OneDrive\Escritorio\scs_v1.2\venv\Lib\site-packages\django\db\models\query.py", line 1847, in _insert
    return query.get_compiler(using=using).execute_sql(returning_fields)
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^
  File "C:\Users\tensa\OneDrive\Escritorio\scs_v1.2\venv\Lib\site-packages\django\db\models\sql\compiler.py", line 1836, in execute_sql
    cursor.execute(sql, params)
    ~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "C:\Users\tensa\OneDrive\Escritorio\scs_v1.2\venv\Lib\site-packages\django\db\backends\utils.py", line 122, in execute
    return super().execute(sql, params)
           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "C:\Users\tensa\OneDrive\Escritorio\scs_v1.2\venv\Lib\site-packages\django\db\backends\utils.py", line 79, in execute
    return self._execute_with_wrappers(
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~^
        sql, params, many=False, executor=self._execute
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "C:\Users\tensa\OneDrive\Escritorio\scs_v1.2\venv\Lib\site-packages\django\db\backends\utils.py", line 92, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "C:\Users\tensa\OneDrive\Escritorio\scs_v1.2\venv\Lib\site-packages\django\db\backends\utils.py", line 100, in _execute
    with self.db.wrap_database_errors:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\tensa\OneDrive\Escritorio\scs_v1.2\venv\Lib\site-packages\django\db\utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "C:\Users\tensa\OneDrive\Escritorio\scs_v1.2\venv\Lib\site-packages\django\db\backends\utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
           ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "C:\Users\tensa\OneDrive\Escritorio\scs_v1.2\venv\Lib\site-packages\django\db\backends\sqlite3\base.py", line 354, in execute
    return super().execute(query, params)
           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
django.db.utils.OperationalError: table produccion_producciondiaria has no column named estado
INFO 2025-01-01 21:12:59,819 autoreload 2168 1452 Watching for file changes with StatReloader
ERROR 2025-01-02 01:41:20,938 log 2168 10628 Internal Server Error: /rrhh/trabajadores/
Traceback (most recent call last):
  File "C:\Users\tensa\OneDrive\Escritorio\scs_v1.2\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\tensa\OneDrive\Escritorio\scs_v1.2\venv\Lib\site-packages\django\core\handlers\base.py", line 220, in _get_response
    response = response.render()
  File "C:\Users\tensa\OneDrive\Escritorio\scs_v1.2\venv\Lib\site-packages\django\template\response.py", line 114, in render
    self.content = self.rendered_content
                   ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\tensa\OneDrive\Escritorio\scs_v1.2\venv\Lib\site-packages\django\template\response.py", line 90, in rendered_content
    template = self.resolve_template(self.template_name)
  File "C:\Users\tensa\OneDrive\Escritorio\scs_v1.2\venv\Lib\site-packages\django\template\response.py", line 72, in resolve_template
    return select_template(template, using=self.using)
  File "C:\Users\tensa\OneDrive\Escritorio\scs_v1.2\venv\Lib\site-packages\django\template\loader.py", line 47, in select_template
    raise TemplateDoesNotExist(", ".join(template_name_list), chain=chain)
django.template.exceptions.TemplateDoesNotExist: rrhh/trabajador_list.html, rrhh/trabajador_list.html
ERROR 2025-01-02 02:52:05,179 log 2168 11108 Internal Server Error: /rrhh/trabajadores/
Traceback (most recent call last):
  File "C:\Users\tensa\OneDrive\Escritorio\scs_v1.2\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\tensa\OneDrive\Escritorio\scs_v1.2\venv\Lib\site-packages\django\core\handlers\base.py", line 220, in _get_response
    response = response.render()
  File "C:\Users\tensa\OneDrive\Escritorio\scs_v1.2\venv\Lib\site-packages\django\template\response.py", line 114, in render
    self.content = self.rendered_content
                   ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\tensa\OneDrive\Escritorio\scs_v1.2\venv\Lib\site-packages\django\template\response.py", line 90, in rendered_content
    template = self.resolve_template(self.template_name)
  File "C:\Users\tensa\OneDrive\Escritorio\scs_v1.2\venv\Lib\site-packages\django\template\response.py", line 72, in resolve_template
    return select_template(template, using=self.using)
  File "C:\Users\tensa\OneDrive\Escritorio\scs_v1.2\venv\Lib\site-packages\django\template\loader.py", line 47, in select_template
    raise TemplateDoesNotExist(", ".join(template_name_list), chain=chain)
django.template.exceptions.TemplateDoesNotExist: rrhh/trabajador_list.html, rrhh/trabajador_list.html
ERROR 2025-01-02 03:18:22,461 log 2168 21716 Internal Server Error: /rrhh/trabajadores/1/
Traceback (most recent call last):
  File "C:\Users\tensa\OneDrive\Escritorio\scs_v1.2\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\tensa\OneDrive\Escritorio\scs_v1.2\venv\Lib\site-packages\django\core\handlers\base.py", line 220, in _get_response
    response = response.render()
  File "C:\Users\tensa\OneDrive\Escritorio\scs_v1.2\venv\Lib\site-packages\django\template\response.py", line 114, in render
    self.content = self.rendered_content
                   ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\tensa\OneDrive\Escritorio\scs_v1.2\venv\Lib\site-packages\django\template\response.py", line 90, in rendered_content
    template = self.resolve_template(self.template_name)
  File "C:\Users\tensa\OneDrive\Escritorio\scs_v1.2\venv\Lib\site-packages\django\template\response.py", line 72, in resolve_template
    return select_template(template, using=self.using)
  File "C:\Users\tensa\OneDrive\Escritorio\scs_v1.2\venv\Lib\site-packages\django\template\loader.py", line 42, in select_template
    return engine.get_template(template_name)
           ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
  File "C:\Users\tensa\OneDrive\Escritorio\scs_v1.2\venv\Lib\site-packages\django\template\backends\django.py", line 79, in get_template
    return Template(self.engine.get_template(template_name), self)
                    ~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
  File "C:\Users\tensa\OneDrive\Escritorio\scs_v1.2\venv\Lib\site-packages\django\template\engine.py", line 177, in get_template
    template, origin = self.find_template(template_name)
                       ~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
  File "C:\Users\tensa\OneDrive\Escritorio\scs_v1.2\venv\Lib\site-packages\django\template\engine.py", line 159, in find_template
    template = loader.get_template(name, skip=skip)
  File "C:\Users\tensa\OneDrive\Escritorio\scs_v1.2\venv\Lib\site-packages\django\template\loaders\cached.py", line 57, in get_template
    template = super().get_template(template_name, skip)
  File "C:\Users\tensa\OneDrive\Escritorio\scs_v1.2\venv\Lib\site-packages\django\template\loaders\base.py", line 28, in get_template
    return Template(
        contents,
    ...<2 lines>...
        self.engine,
    )
  File "C:\Users\tensa\OneDrive\Escritorio\scs_v1.2\venv\Lib\site-packages\django\template\base.py", line 154, in __init__
    self.nodelist = self.compile_nodelist()
                    ~~~~~~~~~~~~~~~~~~~~~^^
  File "C:\Users\tensa\OneDrive\Escritorio\scs_v1.2\venv\Lib\site-packages\django\template\base.py", line 196, in compile_nodelist
    nodelist = parser.parse()
  File "C:\Users\tensa\OneDrive\Escritorio\scs_v1.2\venv\Lib\site-packages\django\template\base.py", line 518, in parse
    raise self.error(token, e)
  File "C:\Users\tensa\OneDrive\Escritorio\scs_v1.2\venv\Lib\site-packages\django\template\base.py", line 516, in parse
    compiled_result = compile_func(self, token)
  File "C:\Users\tensa\OneDrive\Escritorio\scs_v1.2\venv\Lib\site-packages\django\template\loader_tags.py", line 295, in do_extends
    nodelist = parser.parse()
  File "C:\Users\tensa\OneDrive\Escritorio\scs_v1.2\venv\Lib\site-packages\django\template\base.py", line 518, in parse
    raise self.error(token, e)
  File "C:\Users\tensa\OneDrive\Escritorio\scs_v1.2\venv\Lib\site-packages\django\template\base.py", line 516, in parse
    compiled_result = compile_func(self, token)
  File "C:\Users\tensa\OneDrive\Escritorio\scs_v1.2\venv\Lib\site-packages\django\template\loader_tags.py", line 234, in do_block
    nodelist = parser.parse(("endblock",))
  File "C:\Users\tensa\OneDrive\Escritorio\scs_v1.2\venv\Lib\site-packages\django\template\base.py", line 518, in parse
    raise self.error(token, e)
  File "C:\Users\tensa\OneDrive\Escritorio\scs_v1.2\venv\Lib\site-packages\django\template\base.py", line 516, in parse
    compiled_result = compile_func(self, token)
  File "C:\Users\tensa\OneDrive\Escritorio\scs_v1.2\venv\Lib\site-packages\django\template\defaulttags.py", line 962, in do_if
    nodelist = parser.parse(("elif", "else", "endif"))
  File "C:\Users\tensa\OneDrive\Escritorio\scs_v1.2\venv\Lib\site-packages\django\template\base.py", line 518, in parse
    raise self.error(token, e)
  File "C:\Users\tensa\OneDrive\Escritorio\scs_v1.2\venv\Lib\site-packages\django\template\base.py", line 516, in parse
    compiled_result = compile_func(self, token)
  File "C:\Users\tensa\OneDrive\Escritorio\scs_v1.2\venv\Lib\site-packages\django\template\defaulttags.py", line 962, in do_if
    nodelist = parser.parse(("elif", "else", "endif"))
  File "C:\Users\tensa\OneDrive\Escritorio\scs_v1.2\venv\Lib\site-packages\django\template\base.py", line 489, in parse
    raise self.error(token, e)
  File "C:\Users\tensa\OneDrive\Escritorio\scs_v1.2\venv\Lib\site-packages\django\template\base.py", line 487, in parse
    filter_expression = self.compile_filter(token.contents)
  File "C:\Users\tensa\OneDrive\Escritorio\scs_v1.2\venv\Lib\site-packages\django\template\base.py", line 605, in compile_filter
    return FilterExpression(token, self)
  File "C:\Users\tensa\OneDrive\Escritorio\scs_v1.2\venv\Lib\site-packages\django\template\base.py", line 701, in __init__
    filter_func = parser.find_filter(filter_name)
  File "C:\Users\tensa\OneDrive\Escritorio\scs_v1.2\venv\Lib\site-packages\django\template\base.py", line 611, in find_filter
    raise TemplateSyntaxError("Invalid filter: '%s'" % filter_name)
django.template.exceptions.TemplateSyntaxError: Invalid filter: 'intcomma'
ERROR 2025-01-02 03:23:04,656 log 2168 21716 Internal Server Error: /rrhh/trabajadores/1/
Traceback (most recent call last):
  File "C:\Users\tensa\OneDrive\Escritorio\scs_v1.2\venv\Lib\site-packages\django\template\defaulttags.py", line 1035, in find_library
    return parser.libraries[name]
           ~~~~~~~~~~~~~~~~^^^^^^
KeyError: 'humanize'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\tensa\OneDrive\Escritorio\scs_v1.2\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\tensa\OneDrive\Escritorio\scs_v1.2\venv\Lib\site-packages\django\core\handlers\base.py", line 220, in _get_response
    response = response.render()
  File "C:\Users\tensa\OneDrive\Escritorio\scs_v1.2\venv\Lib\site-packages\django\template\response.py", line 114, in render
    self.content = self.rendered_content
                   ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\tensa\OneDrive\Escritorio\scs_v1.2\venv\Lib\site-packages\django\template\response.py", line 90, in rendered_content
    template = self.resolve_template(self.template_name)
  File "C:\Users\tensa\OneDrive\Escritorio\scs_v1.2\venv\Lib\site-packages\django\template\response.py", line 72, in resolve_template
    return select_template(template, using=self.using)
  File "C:\Users\tensa\OneDrive\Escritorio\scs_v1.2\venv\Lib\site-packages\django\template\loader.py", line 42, in select_template
    return engine.get_template(template_name)
           ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
  File "C:\Users\tensa\OneDrive\Escritorio\scs_v1.2\venv\Lib\site-packages\django\template\backends\django.py", line 79, in get_template
    return Template(self.engine.get_template(template_name), self)
                    ~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
  File "C:\Users\tensa\OneDrive\Escritorio\scs_v1.2\venv\Lib\site-packages\django\template\engine.py", line 177, in get_template
    template, origin = self.find_template(template_name)
                       ~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
  File "C:\Users\tensa\OneDrive\Escritorio\scs_v1.2\venv\Lib\site-packages\django\template\engine.py", line 159, in find_template
    template = loader.get_template(name, skip=skip)
  File "C:\Users\tensa\OneDrive\Escritorio\scs_v1.2\venv\Lib\site-packages\django\template\loaders\cached.py", line 57, in get_template
    template = super().get_template(template_name, skip)
  File "C:\Users\tensa\OneDrive\Escritorio\scs_v1.2\venv\Lib\site-packages\django\template\loaders\base.py", line 28, in get_template
    return Template(
        contents,
    ...<2 lines>...
        self.engine,
    )
  File "C:\Users\tensa\OneDrive\Escritorio\scs_v1.2\venv\Lib\site-packages\django\template\base.py", line 154, in __init__
    self.nodelist = self.compile_nodelist()
                    ~~~~~~~~~~~~~~~~~~~~~^^
  File "C:\Users\tensa\OneDrive\Escritorio\scs_v1.2\venv\Lib\site-packages\django\template\base.py", line 196, in compile_nodelist
    nodelist = parser.parse()
  File "C:\Users\tensa\OneDrive\Escritorio\scs_v1.2\venv\Lib\site-packages\django\template\base.py", line 518, in parse
    raise self.error(token, e)
  File "C:\Users\tensa\OneDrive\Escritorio\scs_v1.2\venv\Lib\site-packages\django\template\base.py", line 516, in parse
    compiled_result = compile_func(self, token)
  File "C:\Users\tensa\OneDrive\Escritorio\scs_v1.2\venv\Lib\site-packages\django\template\loader_tags.py", line 295, in do_extends
    nodelist = parser.parse()
  File "C:\Users\tensa\OneDrive\Escritorio\scs_v1.2\venv\Lib\site-packages\django\template\base.py", line 518, in parse
    raise self.error(token, e)
  File "C:\Users\tensa\OneDrive\Escritorio\scs_v1.2\venv\Lib\site-packages\django\template\base.py", line 516, in parse
    compiled_result = compile_func(self, token)
  File "C:\Users\tensa\OneDrive\Escritorio\scs_v1.2\venv\Lib\site-packages\django\template\defaulttags.py", line 1097, in load
    lib = find_library(parser, name)
  File "C:\Users\tensa\OneDrive\Escritorio\scs_v1.2\venv\Lib\site-packages\django\template\defaulttags.py", line 1037, in find_library
    raise TemplateSyntaxError(
    ...<5 lines>...
    )
django.template.exceptions.TemplateSyntaxError: 'humanize' is not a registered tag library. Must be one of:
admin_list
admin_modify
admin_urls
cache
i18n
l10n
log
static
tz
ERROR 2025-01-02 03:23:32,281 log 2168 21716 Internal Server Error: /rrhh/trabajadores/1/
Traceback (most recent call last):
  File "C:\Users\tensa\OneDrive\Escritorio\scs_v1.2\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\tensa\OneDrive\Escritorio\scs_v1.2\venv\Lib\site-packages\django\core\handlers\base.py", line 220, in _get_response
    response = response.render()
  File "C:\Users\tensa\OneDrive\Escritorio\scs_v1.2\venv\Lib\site-packages\django\template\response.py", line 114, in render
    self.content = self.rendered_content
                   ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\tensa\OneDrive\Escritorio\scs_v1.2\venv\Lib\site-packages\django\template\response.py", line 92, in rendered_content
    return template.render(context, self._request)
           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\tensa\OneDrive\Escritorio\scs_v1.2\venv\Lib\site-packages\django\template\backends\django.py", line 107, in render
    return self.template.render(context)
           ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\tensa\OneDrive\Escritorio\scs_v1.2\venv\Lib\site-packages\django\template\base.py", line 171, in render
    return self._render(context)
           ~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\tensa\OneDrive\Escritorio\scs_v1.2\venv\Lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
           ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\tensa\OneDrive\Escritorio\scs_v1.2\venv\Lib\site-packages\django\template\base.py", line 1008, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\tensa\OneDrive\Escritorio\scs_v1.2\venv\Lib\site-packages\django\template\base.py", line 969, in render_annotated
    return self.render(context)
           ~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\tensa\OneDrive\Escritorio\scs_v1.2\venv\Lib\site-packages\django\template\loader_tags.py", line 159, in render
    return compiled_parent._render(context)
           ~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\tensa\OneDrive\Escritorio\scs_v1.2\venv\Lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
           ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\tensa\OneDrive\Escritorio\scs_v1.2\venv\Lib\site-packages\django\template\base.py", line 1008, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\tensa\OneDrive\Escritorio\scs_v1.2\venv\Lib\site-packages\django\template\base.py", line 969, in render_annotated
    return self.render(context)
           ~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\tensa\OneDrive\Escritorio\scs_v1.2\venv\Lib\site-packages\django\template\loader_tags.py", line 65, in render
    result = block.nodelist.render(context)
  File "C:\Users\tensa\OneDrive\Escritorio\scs_v1.2\venv\Lib\site-packages\django\template\base.py", line 1008, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\tensa\OneDrive\Escritorio\scs_v1.2\venv\Lib\site-packages\django\template\base.py", line 969, in render_annotated
    return self.render(context)
           ~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\tensa\OneDrive\Escritorio\scs_v1.2\venv\Lib\site-packages\django\template\defaulttags.py", line 327, in render
    return nodelist.render(context)
           ~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\tensa\OneDrive\Escritorio\scs_v1.2\venv\Lib\site-packages\django\template\base.py", line 1008, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\tensa\OneDrive\Escritorio\scs_v1.2\venv\Lib\site-packages\django\template\base.py", line 969, in render_annotated
    return self.render(context)
           ~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\tensa\OneDrive\Escritorio\scs_v1.2\venv\Lib\site-packages\django\template\defaulttags.py", line 326, in render
    if match:
       ^^^^^
  File "C:\Users\tensa\OneDrive\Escritorio\scs_v1.2\venv\Lib\site-packages\django\db\models\query.py", line 414, in __bool__
    self._fetch_all()
    ~~~~~~~~~~~~~~~^^
  File "C:\Users\tensa\OneDrive\Escritorio\scs_v1.2\venv\Lib\site-packages\django\db\models\query.py", line 1928, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
                         ~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\tensa\OneDrive\Escritorio\scs_v1.2\venv\Lib\site-packages\django\db\models\query.py", line 210, in __iter__
    for row in compiler.results_iter(
               ~~~~~~~~~~~~~~~~~~~~~^
        chunked_fetch=self.chunked_fetch, chunk_size=self.chunk_size
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    ):
    ^
  File "C:\Users\tensa\OneDrive\Escritorio\scs_v1.2\venv\Lib\site-packages\django\db\models\sql\compiler.py", line 1525, in results_iter
    results = self.execute_sql(
        MULTI, chunked_fetch=chunked_fetch, chunk_size=chunk_size
    )
  File "C:\Users\tensa\OneDrive\Escritorio\scs_v1.2\venv\Lib\site-packages\django\db\models\sql\compiler.py", line 1561, in execute_sql
    sql, params = self.as_sql()
                  ~~~~~~~~~~~^^
  File "C:\Users\tensa\OneDrive\Escritorio\scs_v1.2\venv\Lib\site-packages\django\db\models\sql\compiler.py", line 747, in as_sql
    extra_select, order_by, group_by = self.pre_sql_setup(
                                       ~~~~~~~~~~~~~~~~~~^
        with_col_aliases=with_col_aliases or bool(combinator),
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "C:\Users\tensa\OneDrive\Escritorio\scs_v1.2\venv\Lib\site-packages\django\db\models\sql\compiler.py", line 84, in pre_sql_setup
    self.setup_query(with_col_aliases=with_col_aliases)
    ~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\tensa\OneDrive\Escritorio\scs_v1.2\venv\Lib\site-packages\django\db\models\sql\compiler.py", line 73, in setup_query
    self.select, self.klass_info, self.annotation_col_map = self.get_select(
                                                            ~~~~~~~~~~~~~~~^
        with_col_aliases=with_col_aliases,
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "C:\Users\tensa\OneDrive\Escritorio\scs_v1.2\venv\Lib\site-packages\django\db\models\sql\compiler.py", line 309, in get_select
    sql, params = col.select_format(self, sql, params)
                  ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^
  File "C:\Users\tensa\OneDrive\Escritorio\scs_v1.2\venv\Lib\site-packages\django\db\models\expressions.py", line 485, in select_format
    if hasattr(self.output_field, "select_format"):
               ^^^^^^^^^^^^^^^^^
  File "C:\Users\tensa\OneDrive\Escritorio\scs_v1.2\venv\Lib\site-packages\django\utils\functional.py", line 47, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
                                         ~~~~~~~~~^^^^^^^^^^
  File "C:\Users\tensa\OneDrive\Escritorio\scs_v1.2\venv\Lib\site-packages\django\db\models\expressions.py", line 314, in output_field
    output_field = self._resolve_output_field()
  File "C:\Users\tensa\OneDrive\Escritorio\scs_v1.2\venv\Lib\site-packages\django\db\models\expressions.py", line 347, in _resolve_output_field
    source for source in self.get_source_fields() if source is not None
                         ~~~~~~~~~~~~~~~~~~~~~~^^
  File "C:\Users\tensa\OneDrive\Escritorio\scs_v1.2\venv\Lib\site-packages\django\db\models\aggregates.py", line 49, in get_source_fields
    return [e._output_field_or_none for e in super().get_source_expressions()]
            ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\tensa\OneDrive\Escritorio\scs_v1.2\venv\Lib\site-packages\django\utils\functional.py", line 47, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
                                         ~~~~~~~~~^^^^^^^^^^
  File "C:\Users\tensa\OneDrive\Escritorio\scs_v1.2\venv\Lib\site-packages\django\db\models\expressions.py", line 327, in _output_field_or_none
    return self.output_field
           ^^^^^^^^^^^^^^^^^
  File "C:\Users\tensa\OneDrive\Escritorio\scs_v1.2\venv\Lib\site-packages\django\utils\functional.py", line 47, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
                                         ~~~~~~~~~^^^^^^^^^^
  File "C:\Users\tensa\OneDrive\Escritorio\scs_v1.2\venv\Lib\site-packages\django\db\models\expressions.py", line 314, in output_field
    output_field = self._resolve_output_field()
  File "C:\Users\tensa\OneDrive\Escritorio\scs_v1.2\venv\Lib\site-packages\django\db\models\expressions.py", line 728, in _resolve_output_field
    raise FieldError(
    ...<4 lines>...
    )
django.core.exceptions.FieldError: Cannot infer type of '*' expression involving these types: CharField, DecimalField. You must set output_field.
INFO 2025-01-02 03:26:55,307 autoreload 2168 1452 C:\Users\tensa\OneDrive\Escritorio\scs_v1.2\erp_scs\rrhh\views.py changed, reloading.
INFO 2025-01-02 03:26:56,725 autoreload 21868 22488 Watching for file changes with StatReloader
ERROR 2025-01-02 03:27:07,897 log 21868 412 Internal Server Error: /rrhh/trabajadores/1/tarifas/crear/
Traceback (most recent call last):
  File "C:\Users\tensa\OneDrive\Escritorio\scs_v1.2\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\tensa\OneDrive\Escritorio\scs_v1.2\venv\Lib\site-packages\django\core\handlers\base.py", line 220, in _get_response
    response = response.render()
  File "C:\Users\tensa\OneDrive\Escritorio\scs_v1.2\venv\Lib\site-packages\django\template\response.py", line 114, in render
    self.content = self.rendered_content
                   ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\tensa\OneDrive\Escritorio\scs_v1.2\venv\Lib\site-packages\django\template\response.py", line 90, in rendered_content
    template = self.resolve_template(self.template_name)
  File "C:\Users\tensa\OneDrive\Escritorio\scs_v1.2\venv\Lib\site-packages\django\template\response.py", line 72, in resolve_template
    return select_template(template, using=self.using)
  File "C:\Users\tensa\OneDrive\Escritorio\scs_v1.2\venv\Lib\site-packages\django\template\loader.py", line 47, in select_template
    raise TemplateDoesNotExist(", ".join(template_name_list), chain=chain)
django.template.exceptions.TemplateDoesNotExist: rrhh/tarifa_form.html
ERROR 2025-01-02 03:35:42,337 log 21868 21940 Internal Server Error: /rrhh/
Traceback (most recent call last):
  File "C:\Users\tensa\OneDrive\Escritorio\scs_v1.2\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\tensa\OneDrive\Escritorio\scs_v1.2\venv\Lib\site-packages\django\core\handlers\base.py", line 220, in _get_response
    response = response.render()
  File "C:\Users\tensa\OneDrive\Escritorio\scs_v1.2\venv\Lib\site-packages\django\template\response.py", line 114, in render
    self.content = self.rendered_content
                   ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\tensa\OneDrive\Escritorio\scs_v1.2\venv\Lib\site-packages\django\template\response.py", line 92, in rendered_content
    return template.render(context, self._request)
           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\tensa\OneDrive\Escritorio\scs_v1.2\venv\Lib\site-packages\django\template\backends\django.py", line 107, in render
    return self.template.render(context)
           ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\tensa\OneDrive\Escritorio\scs_v1.2\venv\Lib\site-packages\django\template\base.py", line 171, in render
    return self._render(context)
           ~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\tensa\OneDrive\Escritorio\scs_v1.2\venv\Lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
           ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\tensa\OneDrive\Escritorio\scs_v1.2\venv\Lib\site-packages\django\template\base.py", line 1008, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\tensa\OneDrive\Escritorio\scs_v1.2\venv\Lib\site-packages\django\template\base.py", line 969, in render_annotated
    return self.render(context)
           ~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\tensa\OneDrive\Escritorio\scs_v1.2\venv\Lib\site-packages\django\template\loader_tags.py", line 159, in render
    return compiled_parent._render(context)
           ~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\tensa\OneDrive\Escritorio\scs_v1.2\venv\Lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
           ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\tensa\OneDrive\Escritorio\scs_v1.2\venv\Lib\site-packages\django\template\base.py", line 1008, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\tensa\OneDrive\Escritorio\scs_v1.2\venv\Lib\site-packages\django\template\base.py", line 969, in render_annotated
    return self.render(context)
           ~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\tensa\OneDrive\Escritorio\scs_v1.2\venv\Lib\site-packages\django\template\loader_tags.py", line 65, in render
    result = block.nodelist.render(context)
  File "C:\Users\tensa\OneDrive\Escritorio\scs_v1.2\venv\Lib\site-packages\django\template\base.py", line 1008, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\tensa\OneDrive\Escritorio\scs_v1.2\venv\Lib\site-packages\django\template\base.py", line 969, in render_annotated
    return self.render(context)
           ~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\tensa\OneDrive\Escritorio\scs_v1.2\venv\Lib\site-packages\django\template\defaulttags.py", line 480, in render
    url = reverse(view_name, args=args, kwargs=kwargs, current_app=current_app)
  File "C:\Users\tensa\OneDrive\Escritorio\scs_v1.2\venv\Lib\site-packages\django\urls\base.py", line 88, in reverse
    return resolver._reverse_with_prefix(view, prefix, *args, **kwargs)
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\tensa\OneDrive\Escritorio\scs_v1.2\venv\Lib\site-packages\django\urls\resolvers.py", line 831, in _reverse_with_prefix
    raise NoReverseMatch(msg)
django.urls.exceptions.NoReverseMatch: Reverse for 'contrato_create' with no arguments not found. 1 pattern(s) tried: ['rrhh/trabajadores/(?P<trabajador_pk>[0-9]+)/contratos/crear/\\Z']
INFO 2025-01-02 03:37:30,720 autoreload 21868 22488 C:\Users\tensa\OneDrive\Escritorio\scs_v1.2\erp_scs\rrhh\views.py changed, reloading.
INFO 2025-01-02 03:37:31,824 autoreload 6204 23468 Watching for file changes with StatReloader
ERROR 2025-01-02 03:37:35,179 log 6204 22196 Internal Server Error: /rrhh/
Traceback (most recent call last):
  File "C:\Users\tensa\OneDrive\Escritorio\scs_v1.2\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\tensa\OneDrive\Escritorio\scs_v1.2\venv\Lib\site-packages\django\core\handlers\base.py", line 220, in _get_response
    response = response.render()
  File "C:\Users\tensa\OneDrive\Escritorio\scs_v1.2\venv\Lib\site-packages\django\template\response.py", line 114, in render
    self.content = self.rendered_content
                   ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\tensa\OneDrive\Escritorio\scs_v1.2\venv\Lib\site-packages\django\template\response.py", line 92, in rendered_content
    return template.render(context, self._request)
           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\tensa\OneDrive\Escritorio\scs_v1.2\venv\Lib\site-packages\django\template\backends\django.py", line 107, in render
    return self.template.render(context)
           ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\tensa\OneDrive\Escritorio\scs_v1.2\venv\Lib\site-packages\django\template\base.py", line 171, in render
    return self._render(context)
           ~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\tensa\OneDrive\Escritorio\scs_v1.2\venv\Lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
           ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\tensa\OneDrive\Escritorio\scs_v1.2\venv\Lib\site-packages\django\template\base.py", line 1008, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\tensa\OneDrive\Escritorio\scs_v1.2\venv\Lib\site-packages\django\template\base.py", line 969, in render_annotated
    return self.render(context)
           ~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\tensa\OneDrive\Escritorio\scs_v1.2\venv\Lib\site-packages\django\template\loader_tags.py", line 159, in render
    return compiled_parent._render(context)
           ~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\tensa\OneDrive\Escritorio\scs_v1.2\venv\Lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
           ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\tensa\OneDrive\Escritorio\scs_v1.2\venv\Lib\site-packages\django\template\base.py", line 1008, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\tensa\OneDrive\Escritorio\scs_v1.2\venv\Lib\site-packages\django\template\base.py", line 969, in render_annotated
    return self.render(context)
           ~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\tensa\OneDrive\Escritorio\scs_v1.2\venv\Lib\site-packages\django\template\loader_tags.py", line 65, in render
    result = block.nodelist.render(context)
  File "C:\Users\tensa\OneDrive\Escritorio\scs_v1.2\venv\Lib\site-packages\django\template\base.py", line 1008, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\tensa\OneDrive\Escritorio\scs_v1.2\venv\Lib\site-packages\django\template\base.py", line 969, in render_annotated
    return self.render(context)
           ~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\tensa\OneDrive\Escritorio\scs_v1.2\venv\Lib\site-packages\django\template\defaulttags.py", line 480, in render
    url = reverse(view_name, args=args, kwargs=kwargs, current_app=current_app)
  File "C:\Users\tensa\OneDrive\Escritorio\scs_v1.2\venv\Lib\site-packages\django\urls\base.py", line 88, in reverse
    return resolver._reverse_with_prefix(view, prefix, *args, **kwargs)
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\tensa\OneDrive\Escritorio\scs_v1.2\venv\Lib\site-packages\django\urls\resolvers.py", line 831, in _reverse_with_prefix
    raise NoReverseMatch(msg)
django.urls.exceptions.NoReverseMatch: Reverse for 'contrato_create' with no arguments not found. 1 pattern(s) tried: ['rrhh/trabajadores/(?P<trabajador_pk>[0-9]+)/contratos/crear/\\Z']
ERROR 2025-01-02 03:37:44,176 log 6204 22196 Internal Server Error: /rrhh/
Traceback (most recent call last):
  File "C:\Users\tensa\OneDrive\Escritorio\scs_v1.2\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\tensa\OneDrive\Escritorio\scs_v1.2\venv\Lib\site-packages\django\core\handlers\base.py", line 220, in _get_response
    response = response.render()
  File "C:\Users\tensa\OneDrive\Escritorio\scs_v1.2\venv\Lib\site-packages\django\template\response.py", line 114, in render
    self.content = self.rendered_content
                   ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\tensa\OneDrive\Escritorio\scs_v1.2\venv\Lib\site-packages\django\template\response.py", line 92, in rendered_content
    return template.render(context, self._request)
           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\tensa\OneDrive\Escritorio\scs_v1.2\venv\Lib\site-packages\django\template\backends\django.py", line 107, in render
    return self.template.render(context)
           ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\tensa\OneDrive\Escritorio\scs_v1.2\venv\Lib\site-packages\django\template\base.py", line 171, in render
    return self._render(context)
           ~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\tensa\OneDrive\Escritorio\scs_v1.2\venv\Lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
           ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\tensa\OneDrive\Escritorio\scs_v1.2\venv\Lib\site-packages\django\template\base.py", line 1008, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\tensa\OneDrive\Escritorio\scs_v1.2\venv\Lib\site-packages\django\template\base.py", line 969, in render_annotated
    return self.render(context)
           ~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\tensa\OneDrive\Escritorio\scs_v1.2\venv\Lib\site-packages\django\template\loader_tags.py", line 159, in render
    return compiled_parent._render(context)
           ~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\tensa\OneDrive\Escritorio\scs_v1.2\venv\Lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
           ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\tensa\OneDrive\Escritorio\scs_v1.2\venv\Lib\site-packages\django\template\base.py", line 1008, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\tensa\OneDrive\Escritorio\scs_v1.2\venv\Lib\site-packages\django\template\base.py", line 969, in render_annotated
    return self.render(context)
           ~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\tensa\OneDrive\Escritorio\scs_v1.2\venv\Lib\site-packages\django\template\loader_tags.py", line 65, in render
    result = block.nodelist.render(context)
  File "C:\Users\tensa\OneDrive\Escritorio\scs_v1.2\venv\Lib\site-packages\django\template\base.py", line 1008, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\tensa\OneDrive\Escritorio\scs_v1.2\venv\Lib\site-packages\django\template\base.py", line 969, in render_annotated
    return self.render(context)
           ~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\tensa\OneDrive\Escritorio\scs_v1.2\venv\Lib\site-packages\django\template\defaulttags.py", line 480, in render
    url = reverse(view_name, args=args, kwargs=kwargs, current_app=current_app)
  File "C:\Users\tensa\OneDrive\Escritorio\scs_v1.2\venv\Lib\site-packages\django\urls\base.py", line 88, in reverse
    return resolver._reverse_with_prefix(view, prefix, *args, **kwargs)
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\tensa\OneDrive\Escritorio\scs_v1.2\venv\Lib\site-packages\django\urls\resolvers.py", line 831, in _reverse_with_prefix
    raise NoReverseMatch(msg)
django.urls.exceptions.NoReverseMatch: Reverse for 'contrato_create' with no arguments not found. 1 pattern(s) tried: ['rrhh/trabajadores/(?P<trabajador_pk>[0-9]+)/contratos/crear/\\Z']
ERROR 2025-01-02 03:42:38,992 log 6204 22196 Internal Server Error: /rrhh/
Traceback (most recent call last):
  File "C:\Users\tensa\OneDrive\Escritorio\scs_v1.2\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\tensa\OneDrive\Escritorio\scs_v1.2\venv\Lib\site-packages\django\core\handlers\base.py", line 220, in _get_response
    response = response.render()
  File "C:\Users\tensa\OneDrive\Escritorio\scs_v1.2\venv\Lib\site-packages\django\template\response.py", line 114, in render
    self.content = self.rendered_content
                   ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\tensa\OneDrive\Escritorio\scs_v1.2\venv\Lib\site-packages\django\template\response.py", line 92, in rendered_content
    return template.render(context, self._request)
           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\tensa\OneDrive\Escritorio\scs_v1.2\venv\Lib\site-packages\django\template\backends\django.py", line 107, in render
    return self.template.render(context)
           ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\tensa\OneDrive\Escritorio\scs_v1.2\venv\Lib\site-packages\django\template\base.py", line 171, in render
    return self._render(context)
           ~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\tensa\OneDrive\Escritorio\scs_v1.2\venv\Lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
           ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\tensa\OneDrive\Escritorio\scs_v1.2\venv\Lib\site-packages\django\template\base.py", line 1008, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\tensa\OneDrive\Escritorio\scs_v1.2\venv\Lib\site-packages\django\template\base.py", line 969, in render_annotated
    return self.render(context)
           ~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\tensa\OneDrive\Escritorio\scs_v1.2\venv\Lib\site-packages\django\template\loader_tags.py", line 159, in render
    return compiled_parent._render(context)
           ~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\tensa\OneDrive\Escritorio\scs_v1.2\venv\Lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
           ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\tensa\OneDrive\Escritorio\scs_v1.2\venv\Lib\site-packages\django\template\base.py", line 1008, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\tensa\OneDrive\Escritorio\scs_v1.2\venv\Lib\site-packages\django\template\base.py", line 969, in render_annotated
    return self.render(context)
           ~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\tensa\OneDrive\Escritorio\scs_v1.2\venv\Lib\site-packages\django\template\loader_tags.py", line 65, in render
    result = block.nodelist.render(context)
  File "C:\Users\tensa\OneDrive\Escritorio\scs_v1.2\venv\Lib\site-packages\django\template\base.py", line 1008, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\tensa\OneDrive\Escritorio\scs_v1.2\venv\Lib\site-packages\django\template\base.py", line 969, in render_annotated
    return self.render(context)
           ~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\tensa\OneDrive\Escritorio\scs_v1.2\venv\Lib\site-packages\django\template\defaulttags.py", line 480, in render
    url = reverse(view_name, args=args, kwargs=kwargs, current_app=current_app)
  File "C:\Users\tensa\OneDrive\Escritorio\scs_v1.2\venv\Lib\site-packages\django\urls\base.py", line 88, in reverse
    return resolver._reverse_with_prefix(view, prefix, *args, **kwargs)
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\tensa\OneDrive\Escritorio\scs_v1.2\venv\Lib\site-packages\django\urls\resolvers.py", line 831, in _reverse_with_prefix
    raise NoReverseMatch(msg)
django.urls.exceptions.NoReverseMatch: Reverse for 'contrato_create' with no arguments not found. 1 pattern(s) tried: ['rrhh/trabajadores/(?P<trabajador_pk>[0-9]+)/contratos/crear/\\Z']
ERROR 2025-01-02 03:42:42,387 log 6204 22196 Internal Server Error: /rrhh/
Traceback (most recent call last):
  File "C:\Users\tensa\OneDrive\Escritorio\scs_v1.2\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\tensa\OneDrive\Escritorio\scs_v1.2\venv\Lib\site-packages\django\core\handlers\base.py", line 220, in _get_response
    response = response.render()
  File "C:\Users\tensa\OneDrive\Escritorio\scs_v1.2\venv\Lib\site-packages\django\template\response.py", line 114, in render
    self.content = self.rendered_content
                   ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\tensa\OneDrive\Escritorio\scs_v1.2\venv\Lib\site-packages\django\template\response.py", line 92, in rendered_content
    return template.render(context, self._request)
           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\tensa\OneDrive\Escritorio\scs_v1.2\venv\Lib\site-packages\django\template\backends\django.py", line 107, in render
    return self.template.render(context)
           ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\tensa\OneDrive\Escritorio\scs_v1.2\venv\Lib\site-packages\django\template\base.py", line 171, in render
    return self._render(context)
           ~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\tensa\OneDrive\Escritorio\scs_v1.2\venv\Lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
           ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\tensa\OneDrive\Escritorio\scs_v1.2\venv\Lib\site-packages\django\template\base.py", line 1008, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\tensa\OneDrive\Escritorio\scs_v1.2\venv\Lib\site-packages\django\template\base.py", line 969, in render_annotated
    return self.render(context)
           ~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\tensa\OneDrive\Escritorio\scs_v1.2\venv\Lib\site-packages\django\template\loader_tags.py", line 159, in render
    return compiled_parent._render(context)
           ~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\tensa\OneDrive\Escritorio\scs_v1.2\venv\Lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
           ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\tensa\OneDrive\Escritorio\scs_v1.2\venv\Lib\site-packages\django\template\base.py", line 1008, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\tensa\OneDrive\Escritorio\scs_v1.2\venv\Lib\site-packages\django\template\base.py", line 969, in render_annotated
    return self.render(context)
           ~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\tensa\OneDrive\Escritorio\scs_v1.2\venv\Lib\site-packages\django\template\loader_tags.py", line 65, in render
    result = block.nodelist.render(context)
  File "C:\Users\tensa\OneDrive\Escritorio\scs_v1.2\venv\Lib\site-packages\django\template\base.py", line 1008, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\tensa\OneDrive\Escritorio\scs_v1.2\venv\Lib\site-packages\django\template\base.py", line 969, in render_annotated
    return self.render(context)
           ~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\tensa\OneDrive\Escritorio\scs_v1.2\venv\Lib\site-packages\django\template\defaulttags.py", line 480, in render
    url = reverse(view_name, args=args, kwargs=kwargs, current_app=current_app)
  File "C:\Users\tensa\OneDrive\Escritorio\scs_v1.2\venv\Lib\site-packages\django\urls\base.py", line 88, in reverse
    return resolver._reverse_with_prefix(view, prefix, *args, **kwargs)
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\tensa\OneDrive\Escritorio\scs_v1.2\venv\Lib\site-packages\django\urls\resolvers.py", line 831, in _reverse_with_prefix
    raise NoReverseMatch(msg)
django.urls.exceptions.NoReverseMatch: Reverse for 'contrato_create' with no arguments not found. 1 pattern(s) tried: ['rrhh/trabajadores/(?P<trabajador_pk>[0-9]+)/contratos/crear/\\Z']
WARNING 2025-01-02 03:44:28,998 log 6204 22196 Not Found: /rrhh/{
ERROR 2025-01-02 03:45:50,181 log 6204 22196 Internal Server Error: /rrhh/
Traceback (most recent call last):
  File "C:\Users\tensa\OneDrive\Escritorio\scs_v1.2\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\tensa\OneDrive\Escritorio\scs_v1.2\venv\Lib\site-packages\django\core\handlers\base.py", line 220, in _get_response
    response = response.render()
  File "C:\Users\tensa\OneDrive\Escritorio\scs_v1.2\venv\Lib\site-packages\django\template\response.py", line 114, in render
    self.content = self.rendered_content
                   ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\tensa\OneDrive\Escritorio\scs_v1.2\venv\Lib\site-packages\django\template\response.py", line 92, in rendered_content
    return template.render(context, self._request)
           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\tensa\OneDrive\Escritorio\scs_v1.2\venv\Lib\site-packages\django\template\backends\django.py", line 107, in render
    return self.template.render(context)
           ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\tensa\OneDrive\Escritorio\scs_v1.2\venv\Lib\site-packages\django\template\base.py", line 171, in render
    return self._render(context)
           ~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\tensa\OneDrive\Escritorio\scs_v1.2\venv\Lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
           ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\tensa\OneDrive\Escritorio\scs_v1.2\venv\Lib\site-packages\django\template\base.py", line 1008, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\tensa\OneDrive\Escritorio\scs_v1.2\venv\Lib\site-packages\django\template\base.py", line 969, in render_annotated
    return self.render(context)
           ~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\tensa\OneDrive\Escritorio\scs_v1.2\venv\Lib\site-packages\django\template\loader_tags.py", line 159, in render
    return compiled_parent._render(context)
           ~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\tensa\OneDrive\Escritorio\scs_v1.2\venv\Lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
           ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\tensa\OneDrive\Escritorio\scs_v1.2\venv\Lib\site-packages\django\template\base.py", line 1008, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\tensa\OneDrive\Escritorio\scs_v1.2\venv\Lib\site-packages\django\template\base.py", line 969, in render_annotated
    return self.render(context)
           ~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\tensa\OneDrive\Escritorio\scs_v1.2\venv\Lib\site-packages\django\template\loader_tags.py", line 65, in render
    result = block.nodelist.render(context)
  File "C:\Users\tensa\OneDrive\Escritorio\scs_v1.2\venv\Lib\site-packages\django\template\base.py", line 1008, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\tensa\OneDrive\Escritorio\scs_v1.2\venv\Lib\site-packages\django\template\base.py", line 969, in render_annotated
    return self.render(context)
           ~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\tensa\OneDrive\Escritorio\scs_v1.2\venv\Lib\site-packages\django\template\defaulttags.py", line 480, in render
    url = reverse(view_name, args=args, kwargs=kwargs, current_app=current_app)
  File "C:\Users\tensa\OneDrive\Escritorio\scs_v1.2\venv\Lib\site-packages\django\urls\base.py", line 88, in reverse
    return resolver._reverse_with_prefix(view, prefix, *args, **kwargs)
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\tensa\OneDrive\Escritorio\scs_v1.2\venv\Lib\site-packages\django\urls\resolvers.py", line 831, in _reverse_with_prefix
    raise NoReverseMatch(msg)
django.urls.exceptions.NoReverseMatch: Reverse for 'contrato_create' not found. 'contrato_create' is not a valid view function or pattern name.
ERROR 2025-01-02 03:48:58,484 log 6204 22196 Internal Server Error: /rrhh/
Traceback (most recent call last):
  File "C:\Users\tensa\OneDrive\Escritorio\scs_v1.2\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\tensa\OneDrive\Escritorio\scs_v1.2\venv\Lib\site-packages\django\core\handlers\base.py", line 220, in _get_response
    response = response.render()
  File "C:\Users\tensa\OneDrive\Escritorio\scs_v1.2\venv\Lib\site-packages\django\template\response.py", line 114, in render
    self.content = self.rendered_content
                   ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\tensa\OneDrive\Escritorio\scs_v1.2\venv\Lib\site-packages\django\template\response.py", line 92, in rendered_content
    return template.render(context, self._request)
           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\tensa\OneDrive\Escritorio\scs_v1.2\venv\Lib\site-packages\django\template\backends\django.py", line 107, in render
    return self.template.render(context)
           ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\tensa\OneDrive\Escritorio\scs_v1.2\venv\Lib\site-packages\django\template\base.py", line 171, in render
    return self._render(context)
           ~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\tensa\OneDrive\Escritorio\scs_v1.2\venv\Lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
           ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\tensa\OneDrive\Escritorio\scs_v1.2\venv\Lib\site-packages\django\template\base.py", line 1008, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\tensa\OneDrive\Escritorio\scs_v1.2\venv\Lib\site-packages\django\template\base.py", line 969, in render_annotated
    return self.render(context)
           ~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\tensa\OneDrive\Escritorio\scs_v1.2\venv\Lib\site-packages\django\template\loader_tags.py", line 159, in render
    return compiled_parent._render(context)
           ~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\tensa\OneDrive\Escritorio\scs_v1.2\venv\Lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
           ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\tensa\OneDrive\Escritorio\scs_v1.2\venv\Lib\site-packages\django\template\base.py", line 1008, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\tensa\OneDrive\Escritorio\scs_v1.2\venv\Lib\site-packages\django\template\base.py", line 969, in render_annotated
    return self.render(context)
           ~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\tensa\OneDrive\Escritorio\scs_v1.2\venv\Lib\site-packages\django\template\loader_tags.py", line 65, in render
    result = block.nodelist.render(context)
  File "C:\Users\tensa\OneDrive\Escritorio\scs_v1.2\venv\Lib\site-packages\django\template\base.py", line 1008, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\tensa\OneDrive\Escritorio\scs_v1.2\venv\Lib\site-packages\django\template\base.py", line 969, in render_annotated
    return self.render(context)
           ~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\tensa\OneDrive\Escritorio\scs_v1.2\venv\Lib\site-packages\django\template\defaulttags.py", line 480, in render
    url = reverse(view_name, args=args, kwargs=kwargs, current_app=current_app)
  File "C:\Users\tensa\OneDrive\Escritorio\scs_v1.2\venv\Lib\site-packages\django\urls\base.py", line 88, in reverse
    return resolver._reverse_with_prefix(view, prefix, *args, **kwargs)
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\tensa\OneDrive\Escritorio\scs_v1.2\venv\Lib\site-packages\django\urls\resolvers.py", line 831, in _reverse_with_prefix
    raise NoReverseMatch(msg)
django.urls.exceptions.NoReverseMatch: Reverse for 'contrato_create' not found. 'contrato_create' is not a valid view function or pattern name.
ERROR 2025-01-02 03:53:03,631 log 6204 22196 Internal Server Error: /rrhh/trabajadores/1/
Traceback (most recent call last):
  File "C:\Users\tensa\OneDrive\Escritorio\scs_v1.2\venv\Lib\site-packages\django\template\defaulttags.py", line 1035, in find_library
    return parser.libraries[name]
           ~~~~~~~~~~~~~~~~^^^^^^
KeyError: 'humanize'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\tensa\OneDrive\Escritorio\scs_v1.2\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\tensa\OneDrive\Escritorio\scs_v1.2\venv\Lib\site-packages\django\core\handlers\base.py", line 220, in _get_response
    response = response.render()
  File "C:\Users\tensa\OneDrive\Escritorio\scs_v1.2\venv\Lib\site-packages\django\template\response.py", line 114, in render
    self.content = self.rendered_content
                   ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\tensa\OneDrive\Escritorio\scs_v1.2\venv\Lib\site-packages\django\template\response.py", line 90, in rendered_content
    template = self.resolve_template(self.template_name)
  File "C:\Users\tensa\OneDrive\Escritorio\scs_v1.2\venv\Lib\site-packages\django\template\response.py", line 72, in resolve_template
    return select_template(template, using=self.using)
  File "C:\Users\tensa\OneDrive\Escritorio\scs_v1.2\venv\Lib\site-packages\django\template\loader.py", line 42, in select_template
    return engine.get_template(template_name)
           ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
  File "C:\Users\tensa\OneDrive\Escritorio\scs_v1.2\venv\Lib\site-packages\django\template\backends\django.py", line 79, in get_template
    return Template(self.engine.get_template(template_name), self)
                    ~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
  File "C:\Users\tensa\OneDrive\Escritorio\scs_v1.2\venv\Lib\site-packages\django\template\engine.py", line 177, in get_template
    template, origin = self.find_template(template_name)
                       ~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
  File "C:\Users\tensa\OneDrive\Escritorio\scs_v1.2\venv\Lib\site-packages\django\template\engine.py", line 159, in find_template
    template = loader.get_template(name, skip=skip)
  File "C:\Users\tensa\OneDrive\Escritorio\scs_v1.2\venv\Lib\site-packages\django\template\loaders\cached.py", line 57, in get_template
    template = super().get_template(template_name, skip)
  File "C:\Users\tensa\OneDrive\Escritorio\scs_v1.2\venv\Lib\site-packages\django\template\loaders\base.py", line 28, in get_template
    return Template(
        contents,
    ...<2 lines>...
        self.engine,
    )
  File "C:\Users\tensa\OneDrive\Escritorio\scs_v1.2\venv\Lib\site-packages\django\template\base.py", line 154, in __init__
    self.nodelist = self.compile_nodelist()
                    ~~~~~~~~~~~~~~~~~~~~~^^
  File "C:\Users\tensa\OneDrive\Escritorio\scs_v1.2\venv\Lib\site-packages\django\template\base.py", line 196, in compile_nodelist
    nodelist = parser.parse()
  File "C:\Users\tensa\OneDrive\Escritorio\scs_v1.2\venv\Lib\site-packages\django\template\base.py", line 518, in parse
    raise self.error(token, e)
  File "C:\Users\tensa\OneDrive\Escritorio\scs_v1.2\venv\Lib\site-packages\django\template\base.py", line 516, in parse
    compiled_result = compile_func(self, token)
  File "C:\Users\tensa\OneDrive\Escritorio\scs_v1.2\venv\Lib\site-packages\django\template\loader_tags.py", line 295, in do_extends
    nodelist = parser.parse()
  File "C:\Users\tensa\OneDrive\Escritorio\scs_v1.2\venv\Lib\site-packages\django\template\base.py", line 518, in parse
    raise self.error(token, e)
  File "C:\Users\tensa\OneDrive\Escritorio\scs_v1.2\venv\Lib\site-packages\django\template\base.py", line 516, in parse
    compiled_result = compile_func(self, token)
  File "C:\Users\tensa\OneDrive\Escritorio\scs_v1.2\venv\Lib\site-packages\django\template\defaulttags.py", line 1097, in load
    lib = find_library(parser, name)
  File "C:\Users\tensa\OneDrive\Escritorio\scs_v1.2\venv\Lib\site-packages\django\template\defaulttags.py", line 1037, in find_library
    raise TemplateSyntaxError(
    ...<5 lines>...
    )
django.template.exceptions.TemplateSyntaxError: 'humanize' is not a registered tag library. Must be one of:
admin_list
admin_modify
admin_urls
cache
i18n
l10n
log
static
tz
ERROR 2025-01-02 03:53:13,197 log 6204 22196 Internal Server Error: /rrhh/trabajadores/1/
Traceback (most recent call last):
  File "C:\Users\tensa\OneDrive\Escritorio\scs_v1.2\venv\Lib\site-packages\django\template\defaulttags.py", line 1035, in find_library
    return parser.libraries[name]
           ~~~~~~~~~~~~~~~~^^^^^^
KeyError: 'humanize'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\tensa\OneDrive\Escritorio\scs_v1.2\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\tensa\OneDrive\Escritorio\scs_v1.2\venv\Lib\site-packages\django\core\handlers\base.py", line 220, in _get_response
    response = response.render()
  File "C:\Users\tensa\OneDrive\Escritorio\scs_v1.2\venv\Lib\site-packages\django\template\response.py", line 114, in render
    self.content = self.rendered_content
                   ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\tensa\OneDrive\Escritorio\scs_v1.2\venv\Lib\site-packages\django\template\response.py", line 90, in rendered_content
    template = self.resolve_template(self.template_name)
  File "C:\Users\tensa\OneDrive\Escritorio\scs_v1.2\venv\Lib\site-packages\django\template\response.py", line 72, in resolve_template
    return select_template(template, using=self.using)
  File "C:\Users\tensa\OneDrive\Escritorio\scs_v1.2\venv\Lib\site-packages\django\template\loader.py", line 42, in select_template
    return engine.get_template(template_name)
           ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
  File "C:\Users\tensa\OneDrive\Escritorio\scs_v1.2\venv\Lib\site-packages\django\template\backends\django.py", line 79, in get_template
    return Template(self.engine.get_template(template_name), self)
                    ~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
  File "C:\Users\tensa\OneDrive\Escritorio\scs_v1.2\venv\Lib\site-packages\django\template\engine.py", line 177, in get_template
    template, origin = self.find_template(template_name)
                       ~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
  File "C:\Users\tensa\OneDrive\Escritorio\scs_v1.2\venv\Lib\site-packages\django\template\engine.py", line 159, in find_template
    template = loader.get_template(name, skip=skip)
  File "C:\Users\tensa\OneDrive\Escritorio\scs_v1.2\venv\Lib\site-packages\django\template\loaders\cached.py", line 57, in get_template
    template = super().get_template(template_name, skip)
  File "C:\Users\tensa\OneDrive\Escritorio\scs_v1.2\venv\Lib\site-packages\django\template\loaders\base.py", line 28, in get_template
    return Template(
        contents,
    ...<2 lines>...
        self.engine,
    )
  File "C:\Users\tensa\OneDrive\Escritorio\scs_v1.2\venv\Lib\site-packages\django\template\base.py", line 154, in __init__
    self.nodelist = self.compile_nodelist()
                    ~~~~~~~~~~~~~~~~~~~~~^^
  File "C:\Users\tensa\OneDrive\Escritorio\scs_v1.2\venv\Lib\site-packages\django\template\base.py", line 196, in compile_nodelist
    nodelist = parser.parse()
  File "C:\Users\tensa\OneDrive\Escritorio\scs_v1.2\venv\Lib\site-packages\django\template\base.py", line 518, in parse
    raise self.error(token, e)
  File "C:\Users\tensa\OneDrive\Escritorio\scs_v1.2\venv\Lib\site-packages\django\template\base.py", line 516, in parse
    compiled_result = compile_func(self, token)
  File "C:\Users\tensa\OneDrive\Escritorio\scs_v1.2\venv\Lib\site-packages\django\template\loader_tags.py", line 295, in do_extends
    nodelist = parser.parse()
  File "C:\Users\tensa\OneDrive\Escritorio\scs_v1.2\venv\Lib\site-packages\django\template\base.py", line 518, in parse
    raise self.error(token, e)
  File "C:\Users\tensa\OneDrive\Escritorio\scs_v1.2\venv\Lib\site-packages\django\template\base.py", line 516, in parse
    compiled_result = compile_func(self, token)
  File "C:\Users\tensa\OneDrive\Escritorio\scs_v1.2\venv\Lib\site-packages\django\template\defaulttags.py", line 1097, in load
    lib = find_library(parser, name)
  File "C:\Users\tensa\OneDrive\Escritorio\scs_v1.2\venv\Lib\site-packages\django\template\defaulttags.py", line 1037, in find_library
    raise TemplateSyntaxError(
    ...<5 lines>...
    )
django.template.exceptions.TemplateSyntaxError: 'humanize' is not a registered tag library. Must be one of:
admin_list
admin_modify
admin_urls
cache
i18n
l10n
log
static
tz
INFO 2025-01-02 03:55:13,569 autoreload 6204 23468 C:\Users\tensa\OneDrive\Escritorio\scs_v1.2\erp_scs\rrhh\urls.py changed, reloading.
INFO 2025-01-02 03:55:14,689 autoreload 22968 15736 Watching for file changes with StatReloader
INFO 2025-01-02 04:00:19,277 autoreload 22968 15736 C:\Users\tensa\OneDrive\Escritorio\scs_v1.2\erp_scs\rrhh\views.py changed, reloading.
INFO 2025-01-02 04:00:20,325 autoreload 17720 9228 Watching for file changes with StatReloader
INFO 2025-01-02 04:01:56,007 autoreload 17720 9228 C:\Users\tensa\OneDrive\Escritorio\scs_v1.2\erp_scs\rrhh\urls.py changed, reloading.
INFO 2025-01-02 04:01:57,123 autoreload 7468 10068 Watching for file changes with StatReloader
WARNING 2025-01-02 04:02:11,913 log 7468 3588 Not Found: /rrhh/{
WARNING 2025-01-02 04:02:58,028 log 7468 3588 Not Found: /rrhh/{
WARNING 2025-01-02 04:03:57,271 log 7468 3588 Not Found: /rrhh/{
INFO 2025-01-02 04:07:59,755 autoreload 7468 10068 C:\Users\tensa\OneDrive\Escritorio\scs_v1.2\erp_scs\rrhh\urls.py changed, reloading.
INFO 2025-01-02 04:08:00,850 autoreload 14364 22492 Watching for file changes with StatReloader
WARNING 2025-01-02 04:08:08,453 log 14364 21656 Not Found: /rrhh/{
WARNING 2025-01-02 04:09:06,126 log 14364 21656 Not Found: /rrhh/{
WARNING 2025-01-02 04:11:31,791 log 14364 21656 Not Found: /rrhh/{
INFO 2025-01-02 04:17:22,348 autoreload 14364 22492 C:\Users\tensa\OneDrive\Escritorio\scs_v1.2\erp_scs\rrhh\views.py changed, reloading.
INFO 2025-01-02 04:17:23,475 autoreload 23476 13132 Watching for file changes with StatReloader
WARNING 2025-01-02 04:17:34,114 log 23476 19984 Not Found: /rrhh/{
WARNING 2025-01-02 04:21:10,256 log 23476 19984 Not Found: /rrhh/{
WARNING 2025-01-02 04:21:12,085 log 23476 19984 Not Found: /rrhh/{
INFO 2025-01-02 04:23:23,694 autoreload 23476 13132 C:\Users\tensa\OneDrive\Escritorio\scs_v1.2\erp_scs\rrhh\views.py changed, reloading.
INFO 2025-01-02 04:23:24,765 autoreload 19636 20908 Watching for file changes with StatReloader
WARNING 2025-01-02 04:23:32,870 log 19636 17916 Not Found: /rrhh/{
WARNING 2025-01-02 04:26:23,933 log 19636 17916 Not Found: /rrhh/{
INFO 2025-01-02 04:28:21,884 autoreload 15500 22188 Watching for file changes with StatReloader
ERROR 2025-01-02 04:42:08,990 log 15500 23100 Internal Server Error: /rrhh/produccion/
Traceback (most recent call last):
  File "C:\Users\tensa\OneDrive\Escritorio\scs_v1.2\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\tensa\OneDrive\Escritorio\scs_v1.2\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\tensa\OneDrive\Escritorio\scs_v1.2\venv\Lib\site-packages\django\views\generic\base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
           ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\tensa\OneDrive\Escritorio\scs_v1.2\venv\Lib\site-packages\django\contrib\auth\mixins.py", line 73, in dispatch
    return super().dispatch(request, *args, **kwargs)
           ~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\tensa\OneDrive\Escritorio\scs_v1.2\venv\Lib\site-packages\django\contrib\auth\mixins.py", line 109, in dispatch
    return super().dispatch(request, *args, **kwargs)
           ~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\tensa\OneDrive\Escritorio\scs_v1.2\venv\Lib\site-packages\django\views\generic\base.py", line 143, in dispatch
    return handler(request, *args, **kwargs)
  File "C:\Users\tensa\OneDrive\Escritorio\scs_v1.2\venv\Lib\site-packages\django\views\generic\list.py", line 174, in get
    context = self.get_context_data()
  File "C:\Users\tensa\OneDrive\Escritorio\scs_v1.2\erp_scs\rrhh\views.py", line 443, in get_context_data
    if context['producciones']:
       ~~~~~~~^^^^^^^^^^^^^^^^
  File "C:\Users\tensa\OneDrive\Escritorio\scs_v1.2\venv\Lib\site-packages\django\db\models\query.py", line 414, in __bool__
    self._fetch_all()
    ~~~~~~~~~~~~~~~^^
  File "C:\Users\tensa\OneDrive\Escritorio\scs_v1.2\venv\Lib\site-packages\django\db\models\query.py", line 1928, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
                         ~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\tensa\OneDrive\Escritorio\scs_v1.2\venv\Lib\site-packages\django\db\models\query.py", line 91, in __iter__
    results = compiler.execute_sql(
        chunked_fetch=self.chunked_fetch, chunk_size=self.chunk_size
    )
  File "C:\Users\tensa\OneDrive\Escritorio\scs_v1.2\venv\Lib\site-packages\django\db\models\sql\compiler.py", line 1561, in execute_sql
    sql, params = self.as_sql()
                  ~~~~~~~~~~~^^
  File "C:\Users\tensa\OneDrive\Escritorio\scs_v1.2\venv\Lib\site-packages\django\db\models\sql\compiler.py", line 747, in as_sql
    extra_select, order_by, group_by = self.pre_sql_setup(
                                       ~~~~~~~~~~~~~~~~~~^
        with_col_aliases=with_col_aliases or bool(combinator),
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "C:\Users\tensa\OneDrive\Escritorio\scs_v1.2\venv\Lib\site-packages\django\db\models\sql\compiler.py", line 84, in pre_sql_setup
    self.setup_query(with_col_aliases=with_col_aliases)
    ~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\tensa\OneDrive\Escritorio\scs_v1.2\venv\Lib\site-packages\django\db\models\sql\compiler.py", line 73, in setup_query
    self.select, self.klass_info, self.annotation_col_map = self.get_select(
                                                            ~~~~~~~~~~~~~~~^
        with_col_aliases=with_col_aliases,
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "C:\Users\tensa\OneDrive\Escritorio\scs_v1.2\venv\Lib\site-packages\django\db\models\sql\compiler.py", line 279, in get_select
    related_klass_infos = self.get_related_selections(select, select_mask)
  File "C:\Users\tensa\OneDrive\Escritorio\scs_v1.2\venv\Lib\site-packages\django\db\models\sql\compiler.py", line 1248, in get_related_selections
    next_klass_infos = self.get_related_selections(
        select,
    ...<5 lines>...
        restricted,
    )
  File "C:\Users\tensa\OneDrive\Escritorio\scs_v1.2\venv\Lib\site-packages\django\db\models\sql\compiler.py", line 1379, in get_related_selections
    raise FieldError(
    ...<6 lines>...
    )
django.core.exceptions.FieldError: Invalid field name(s) given in select_related: 'usuario'. Choices are: perfil_trabajador
ERROR 2025-01-02 04:47:39,845 log 15500 19572 Internal Server Error: /rrhh/produccion/
Traceback (most recent call last):
  File "C:\Users\tensa\OneDrive\Escritorio\scs_v1.2\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\tensa\OneDrive\Escritorio\scs_v1.2\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\tensa\OneDrive\Escritorio\scs_v1.2\venv\Lib\site-packages\django\views\generic\base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
           ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\tensa\OneDrive\Escritorio\scs_v1.2\venv\Lib\site-packages\django\contrib\auth\mixins.py", line 73, in dispatch
    return super().dispatch(request, *args, **kwargs)
           ~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\tensa\OneDrive\Escritorio\scs_v1.2\venv\Lib\site-packages\django\contrib\auth\mixins.py", line 109, in dispatch
    return super().dispatch(request, *args, **kwargs)
           ~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\tensa\OneDrive\Escritorio\scs_v1.2\venv\Lib\site-packages\django\views\generic\base.py", line 143, in dispatch
    return handler(request, *args, **kwargs)
  File "C:\Users\tensa\OneDrive\Escritorio\scs_v1.2\venv\Lib\site-packages\django\views\generic\list.py", line 174, in get
    context = self.get_context_data()
  File "C:\Users\tensa\OneDrive\Escritorio\scs_v1.2\erp_scs\rrhh\views.py", line 443, in get_context_data
    if context['producciones']:
       ~~~~~~~^^^^^^^^^^^^^^^^
  File "C:\Users\tensa\OneDrive\Escritorio\scs_v1.2\venv\Lib\site-packages\django\db\models\query.py", line 414, in __bool__
    self._fetch_all()
    ~~~~~~~~~~~~~~~^^
  File "C:\Users\tensa\OneDrive\Escritorio\scs_v1.2\venv\Lib\site-packages\django\db\models\query.py", line 1928, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
                         ~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\tensa\OneDrive\Escritorio\scs_v1.2\venv\Lib\site-packages\django\db\models\query.py", line 91, in __iter__
    results = compiler.execute_sql(
        chunked_fetch=self.chunked_fetch, chunk_size=self.chunk_size
    )
  File "C:\Users\tensa\OneDrive\Escritorio\scs_v1.2\venv\Lib\site-packages\django\db\models\sql\compiler.py", line 1561, in execute_sql
    sql, params = self.as_sql()
                  ~~~~~~~~~~~^^
  File "C:\Users\tensa\OneDrive\Escritorio\scs_v1.2\venv\Lib\site-packages\django\db\models\sql\compiler.py", line 747, in as_sql
    extra_select, order_by, group_by = self.pre_sql_setup(
                                       ~~~~~~~~~~~~~~~~~~^
        with_col_aliases=with_col_aliases or bool(combinator),
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "C:\Users\tensa\OneDrive\Escritorio\scs_v1.2\venv\Lib\site-packages\django\db\models\sql\compiler.py", line 84, in pre_sql_setup
    self.setup_query(with_col_aliases=with_col_aliases)
    ~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\tensa\OneDrive\Escritorio\scs_v1.2\venv\Lib\site-packages\django\db\models\sql\compiler.py", line 73, in setup_query
    self.select, self.klass_info, self.annotation_col_map = self.get_select(
                                                            ~~~~~~~~~~~~~~~^
        with_col_aliases=with_col_aliases,
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "C:\Users\tensa\OneDrive\Escritorio\scs_v1.2\venv\Lib\site-packages\django\db\models\sql\compiler.py", line 279, in get_select
    related_klass_infos = self.get_related_selections(select, select_mask)
  File "C:\Users\tensa\OneDrive\Escritorio\scs_v1.2\venv\Lib\site-packages\django\db\models\sql\compiler.py", line 1248, in get_related_selections
    next_klass_infos = self.get_related_selections(
        select,
    ...<5 lines>...
        restricted,
    )
  File "C:\Users\tensa\OneDrive\Escritorio\scs_v1.2\venv\Lib\site-packages\django\db\models\sql\compiler.py", line 1379, in get_related_selections
    raise FieldError(
    ...<6 lines>...
    )
django.core.exceptions.FieldError: Invalid field name(s) given in select_related: 'usuario'. Choices are: perfil_trabajador
INFO 2025-01-02 04:51:19,316 autoreload 15500 22188 C:\Users\tensa\OneDrive\Escritorio\scs_v1.2\erp_scs\rrhh\views.py changed, reloading.
INFO 2025-01-02 04:51:20,400 autoreload 2712 8972 Watching for file changes with StatReloader
ERROR 2025-01-02 04:51:26,191 log 2712 22104 Internal Server Error: /rrhh/produccion/
Traceback (most recent call last):
  File "C:\Users\tensa\OneDrive\Escritorio\scs_v1.2\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\tensa\OneDrive\Escritorio\scs_v1.2\venv\Lib\site-packages\django\core\handlers\base.py", line 220, in _get_response
    response = response.render()
  File "C:\Users\tensa\OneDrive\Escritorio\scs_v1.2\venv\Lib\site-packages\django\template\response.py", line 114, in render
    self.content = self.rendered_content
                   ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\tensa\OneDrive\Escritorio\scs_v1.2\venv\Lib\site-packages\django\template\response.py", line 90, in rendered_content
    template = self.resolve_template(self.template_name)
  File "C:\Users\tensa\OneDrive\Escritorio\scs_v1.2\venv\Lib\site-packages\django\template\response.py", line 72, in resolve_template
    return select_template(template, using=self.using)
  File "C:\Users\tensa\OneDrive\Escritorio\scs_v1.2\venv\Lib\site-packages\django\template\loader.py", line 47, in select_template
    raise TemplateDoesNotExist(", ".join(template_name_list), chain=chain)
django.template.exceptions.TemplateDoesNotExist: rrhh/produccion_trabajador_list.html, produccion/producciondiaria_list.html
ERROR 2025-01-02 04:51:36,238 log 2712 22104 Internal Server Error: /rrhh/produccion/
Traceback (most recent call last):
  File "C:\Users\tensa\OneDrive\Escritorio\scs_v1.2\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\tensa\OneDrive\Escritorio\scs_v1.2\venv\Lib\site-packages\django\core\handlers\base.py", line 220, in _get_response
    response = response.render()
  File "C:\Users\tensa\OneDrive\Escritorio\scs_v1.2\venv\Lib\site-packages\django\template\response.py", line 114, in render
    self.content = self.rendered_content
                   ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\tensa\OneDrive\Escritorio\scs_v1.2\venv\Lib\site-packages\django\template\response.py", line 90, in rendered_content
    template = self.resolve_template(self.template_name)
  File "C:\Users\tensa\OneDrive\Escritorio\scs_v1.2\venv\Lib\site-packages\django\template\response.py", line 72, in resolve_template
    return select_template(template, using=self.using)
  File "C:\Users\tensa\OneDrive\Escritorio\scs_v1.2\venv\Lib\site-packages\django\template\loader.py", line 47, in select_template
    raise TemplateDoesNotExist(", ".join(template_name_list), chain=chain)
django.template.exceptions.TemplateDoesNotExist: rrhh/produccion_trabajador_list.html, produccion/producciondiaria_list.html
WARNING 2025-01-02 05:06:43,724 log 2712 1408 Not Found: /rrhh/{% url 'rrhh:tarifa_create'}
INFO 2025-01-02 05:08:25,292 autoreload 2712 8972 C:\Users\tensa\OneDrive\Escritorio\scs_v1.2\erp_scs\rrhh\views.py changed, reloading.
INFO 2025-01-02 05:08:26,335 autoreload 21860 6336 Watching for file changes with StatReloader
WARNING 2025-01-02 05:08:31,435 log 21860 4248 Not Found: /rrhh/{% url 'rrhh:tarifa_create'}
WARNING 2025-01-02 05:08:40,414 log 21860 4248 Not Found: /rrhh/{% url 'rrhh:tarifa_create'}
WARNING 2025-01-02 05:09:23,038 log 21860 4248 Not Found: /rrhh/{% url 'rrhh:tarifa_create'}
WARNING 2025-01-02 05:09:27,523 log 21860 4248 Not Found: /rrhh/{% url 'rrhh:tarifa_create'}
INFO 2025-01-02 05:10:18,559 autoreload 20800 21788 Watching for file changes with StatReloader
WARNING 2025-01-02 05:10:22,613 log 20800 22676 Not Found: /rrhh/{% url 'rrhh:tarifa_create'}
WARNING 2025-01-02 05:15:41,734 log 20800 12768 Not Found: /rrhh/{% url 'rrhh:tarifa_create'}
WARNING 2025-01-02 05:15:47,662 log 20800 12768 Not Found: /rrhh/{% url 'rrhh:tarifa_create'}
ERROR 2025-01-02 05:30:03,672 log 20800 16184 Internal Server Error: /rrhh/trabajadores/1/
Traceback (most recent call last):
  File "C:\Users\tensa\OneDrive\Escritorio\scs_v1.2\venv\Lib\site-packages\django\template\defaulttags.py", line 1035, in find_library
    return parser.libraries[name]
           ~~~~~~~~~~~~~~~~^^^^^^
KeyError: 'humanize'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\tensa\OneDrive\Escritorio\scs_v1.2\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\tensa\OneDrive\Escritorio\scs_v1.2\venv\Lib\site-packages\django\core\handlers\base.py", line 220, in _get_response
    response = response.render()
  File "C:\Users\tensa\OneDrive\Escritorio\scs_v1.2\venv\Lib\site-packages\django\template\response.py", line 114, in render
    self.content = self.rendered_content
                   ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\tensa\OneDrive\Escritorio\scs_v1.2\venv\Lib\site-packages\django\template\response.py", line 90, in rendered_content
    template = self.resolve_template(self.template_name)
  File "C:\Users\tensa\OneDrive\Escritorio\scs_v1.2\venv\Lib\site-packages\django\template\response.py", line 72, in resolve_template
    return select_template(template, using=self.using)
  File "C:\Users\tensa\OneDrive\Escritorio\scs_v1.2\venv\Lib\site-packages\django\template\loader.py", line 42, in select_template
    return engine.get_template(template_name)
           ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
  File "C:\Users\tensa\OneDrive\Escritorio\scs_v1.2\venv\Lib\site-packages\django\template\backends\django.py", line 79, in get_template
    return Template(self.engine.get_template(template_name), self)
                    ~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
  File "C:\Users\tensa\OneDrive\Escritorio\scs_v1.2\venv\Lib\site-packages\django\template\engine.py", line 177, in get_template
    template, origin = self.find_template(template_name)
                       ~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
  File "C:\Users\tensa\OneDrive\Escritorio\scs_v1.2\venv\Lib\site-packages\django\template\engine.py", line 159, in find_template
    template = loader.get_template(name, skip=skip)
  File "C:\Users\tensa\OneDrive\Escritorio\scs_v1.2\venv\Lib\site-packages\django\template\loaders\cached.py", line 57, in get_template
    template = super().get_template(template_name, skip)
  File "C:\Users\tensa\OneDrive\Escritorio\scs_v1.2\venv\Lib\site-packages\django\template\loaders\base.py", line 28, in get_template
    return Template(
        contents,
    ...<2 lines>...
        self.engine,
    )
  File "C:\Users\tensa\OneDrive\Escritorio\scs_v1.2\venv\Lib\site-packages\django\template\base.py", line 154, in __init__
    self.nodelist = self.compile_nodelist()
                    ~~~~~~~~~~~~~~~~~~~~~^^
  File "C:\Users\tensa\OneDrive\Escritorio\scs_v1.2\venv\Lib\site-packages\django\template\base.py", line 196, in compile_nodelist
    nodelist = parser.parse()
  File "C:\Users\tensa\OneDrive\Escritorio\scs_v1.2\venv\Lib\site-packages\django\template\base.py", line 518, in parse
    raise self.error(token, e)
  File "C:\Users\tensa\OneDrive\Escritorio\scs_v1.2\venv\Lib\site-packages\django\template\base.py", line 516, in parse
    compiled_result = compile_func(self, token)
  File "C:\Users\tensa\OneDrive\Escritorio\scs_v1.2\venv\Lib\site-packages\django\template\loader_tags.py", line 295, in do_extends
    nodelist = parser.parse()
  File "C:\Users\tensa\OneDrive\Escritorio\scs_v1.2\venv\Lib\site-packages\django\template\base.py", line 518, in parse
    raise self.error(token, e)
  File "C:\Users\tensa\OneDrive\Escritorio\scs_v1.2\venv\Lib\site-packages\django\template\base.py", line 516, in parse
    compiled_result = compile_func(self, token)
  File "C:\Users\tensa\OneDrive\Escritorio\scs_v1.2\venv\Lib\site-packages\django\template\defaulttags.py", line 1097, in load
    lib = find_library(parser, name)
  File "C:\Users\tensa\OneDrive\Escritorio\scs_v1.2\venv\Lib\site-packages\django\template\defaulttags.py", line 1037, in find_library
    raise TemplateSyntaxError(
    ...<5 lines>...
    )
django.template.exceptions.TemplateSyntaxError: 'humanize' is not a registered tag library. Must be one of:
admin_list
admin_modify
admin_urls
cache
i18n
l10n
log
static
tz
INFO 2025-01-02 05:32:57,379 autoreload 10064 1692 Watching for file changes with StatReloader
ERROR 2025-01-02 05:34:03,866 log 10064 15964 Internal Server Error: /rrhh/
Traceback (most recent call last):
  File "C:\Users\tensa\OneDrive\Escritorio\scs_v1.2\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\tensa\OneDrive\Escritorio\scs_v1.2\venv\Lib\site-packages\django\core\handlers\base.py", line 220, in _get_response
    response = response.render()
  File "C:\Users\tensa\OneDrive\Escritorio\scs_v1.2\venv\Lib\site-packages\django\template\response.py", line 114, in render
    self.content = self.rendered_content
                   ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\tensa\OneDrive\Escritorio\scs_v1.2\venv\Lib\site-packages\django\template\response.py", line 92, in rendered_content
    return template.render(context, self._request)
           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\tensa\OneDrive\Escritorio\scs_v1.2\venv\Lib\site-packages\django\template\backends\django.py", line 107, in render
    return self.template.render(context)
           ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\tensa\OneDrive\Escritorio\scs_v1.2\venv\Lib\site-packages\django\template\base.py", line 171, in render
    return self._render(context)
           ~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\tensa\OneDrive\Escritorio\scs_v1.2\venv\Lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
           ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\tensa\OneDrive\Escritorio\scs_v1.2\venv\Lib\site-packages\django\template\base.py", line 1008, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\tensa\OneDrive\Escritorio\scs_v1.2\venv\Lib\site-packages\django\template\base.py", line 969, in render_annotated
    return self.render(context)
           ~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\tensa\OneDrive\Escritorio\scs_v1.2\venv\Lib\site-packages\django\template\loader_tags.py", line 159, in render
    return compiled_parent._render(context)
           ~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\tensa\OneDrive\Escritorio\scs_v1.2\venv\Lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
           ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\tensa\OneDrive\Escritorio\scs_v1.2\venv\Lib\site-packages\django\template\base.py", line 1008, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\tensa\OneDrive\Escritorio\scs_v1.2\venv\Lib\site-packages\django\template\base.py", line 969, in render_annotated
    return self.render(context)
           ~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\tensa\OneDrive\Escritorio\scs_v1.2\venv\Lib\site-packages\django\template\loader_tags.py", line 65, in render
    result = block.nodelist.render(context)
  File "C:\Users\tensa\OneDrive\Escritorio\scs_v1.2\venv\Lib\site-packages\django\template\base.py", line 1008, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\tensa\OneDrive\Escritorio\scs_v1.2\venv\Lib\site-packages\django\template\base.py", line 969, in render_annotated
    return self.render(context)
           ~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\tensa\OneDrive\Escritorio\scs_v1.2\venv\Lib\site-packages\django\template\defaulttags.py", line 480, in render
    url = reverse(view_name, args=args, kwargs=kwargs, current_app=current_app)
  File "C:\Users\tensa\OneDrive\Escritorio\scs_v1.2\venv\Lib\site-packages\django\urls\base.py", line 88, in reverse
    return resolver._reverse_with_prefix(view, prefix, *args, **kwargs)
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\tensa\OneDrive\Escritorio\scs_v1.2\venv\Lib\site-packages\django\urls\resolvers.py", line 831, in _reverse_with_prefix
    raise NoReverseMatch(msg)
django.urls.exceptions.NoReverseMatch: Reverse for 'tarifa_create' with no arguments not found. 1 pattern(s) tried: ['rrhh/trabajadores/(?P<trabajador_pk>[0-9]+)/tarifas/crear/\\Z']
INFO 2025-01-02 14:36:57,369 autoreload 10064 1692 C:\Users\tensa\OneDrive\Escritorio\scs_v1.2\erp_scs\rrhh\views.py changed, reloading.
INFO 2025-01-02 14:36:59,186 autoreload 9224 12160 Watching for file changes with StatReloader
ERROR 2025-01-02 14:44:40,079 log 9224 23264 Internal Server Error: /rrhh/
Traceback (most recent call last):
  File "C:\Users\tensa\OneDrive\Escritorio\scs_v1.2\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\tensa\OneDrive\Escritorio\scs_v1.2\venv\Lib\site-packages\django\core\handlers\base.py", line 220, in _get_response
    response = response.render()
  File "C:\Users\tensa\OneDrive\Escritorio\scs_v1.2\venv\Lib\site-packages\django\template\response.py", line 114, in render
    self.content = self.rendered_content
                   ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\tensa\OneDrive\Escritorio\scs_v1.2\venv\Lib\site-packages\django\template\response.py", line 92, in rendered_content
    return template.render(context, self._request)
           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\tensa\OneDrive\Escritorio\scs_v1.2\venv\Lib\site-packages\django\template\backends\django.py", line 107, in render
    return self.template.render(context)
           ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\tensa\OneDrive\Escritorio\scs_v1.2\venv\Lib\site-packages\django\template\base.py", line 171, in render
    return self._render(context)
           ~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\tensa\OneDrive\Escritorio\scs_v1.2\venv\Lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
           ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\tensa\OneDrive\Escritorio\scs_v1.2\venv\Lib\site-packages\django\template\base.py", line 1008, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\tensa\OneDrive\Escritorio\scs_v1.2\venv\Lib\site-packages\django\template\base.py", line 969, in render_annotated
    return self.render(context)
           ~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\tensa\OneDrive\Escritorio\scs_v1.2\venv\Lib\site-packages\django\template\loader_tags.py", line 159, in render
    return compiled_parent._render(context)
           ~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\tensa\OneDrive\Escritorio\scs_v1.2\venv\Lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
           ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\tensa\OneDrive\Escritorio\scs_v1.2\venv\Lib\site-packages\django\template\base.py", line 1008, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\tensa\OneDrive\Escritorio\scs_v1.2\venv\Lib\site-packages\django\template\base.py", line 969, in render_annotated
    return self.render(context)
           ~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\tensa\OneDrive\Escritorio\scs_v1.2\venv\Lib\site-packages\django\template\loader_tags.py", line 65, in render
    result = block.nodelist.render(context)
  File "C:\Users\tensa\OneDrive\Escritorio\scs_v1.2\venv\Lib\site-packages\django\template\base.py", line 1008, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\tensa\OneDrive\Escritorio\scs_v1.2\venv\Lib\site-packages\django\template\base.py", line 969, in render_annotated
    return self.render(context)
           ~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\tensa\OneDrive\Escritorio\scs_v1.2\venv\Lib\site-packages\django\template\defaulttags.py", line 480, in render
    url = reverse(view_name, args=args, kwargs=kwargs, current_app=current_app)
  File "C:\Users\tensa\OneDrive\Escritorio\scs_v1.2\venv\Lib\site-packages\django\urls\base.py", line 88, in reverse
    return resolver._reverse_with_prefix(view, prefix, *args, **kwargs)
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\tensa\OneDrive\Escritorio\scs_v1.2\venv\Lib\site-packages\django\urls\resolvers.py", line 831, in _reverse_with_prefix
    raise NoReverseMatch(msg)
django.urls.exceptions.NoReverseMatch: Reverse for 'produccion_trabajador_list' not found. 'produccion_trabajador_list' is not a valid view function or pattern name.
INFO 2025-01-02 14:48:40,399 autoreload 9224 12160 C:\Users\tensa\OneDrive\Escritorio\scs_v1.2\erp_scs\rrhh\urls.py changed, reloading.
INFO 2025-01-02 14:48:42,615 autoreload 10628 19372 Watching for file changes with StatReloader
ERROR 2025-01-02 14:48:54,529 log 10628 23496 Internal Server Error: /rrhh/produccion/trabajadores/
Traceback (most recent call last):
  File "C:\Users\tensa\OneDrive\Escritorio\scs_v1.2\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\tensa\OneDrive\Escritorio\scs_v1.2\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\tensa\OneDrive\Escritorio\scs_v1.2\venv\Lib\site-packages\django\views\generic\base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
           ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\tensa\OneDrive\Escritorio\scs_v1.2\venv\Lib\site-packages\django\contrib\auth\mixins.py", line 73, in dispatch
    return super().dispatch(request, *args, **kwargs)
           ~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\tensa\OneDrive\Escritorio\scs_v1.2\venv\Lib\site-packages\django\contrib\auth\mixins.py", line 109, in dispatch
    return super().dispatch(request, *args, **kwargs)
           ~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\tensa\OneDrive\Escritorio\scs_v1.2\venv\Lib\site-packages\django\views\generic\base.py", line 143, in dispatch
    return handler(request, *args, **kwargs)
  File "C:\Users\tensa\OneDrive\Escritorio\scs_v1.2\venv\Lib\site-packages\django\views\generic\list.py", line 174, in get
    context = self.get_context_data()
  File "C:\Users\tensa\OneDrive\Escritorio\scs_v1.2\erp_scs\rrhh\views.py", line 481, in get_context_data
    dias_produccion = context['producciones'].values('fecha').distinct().count()
                      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "C:\Users\tensa\OneDrive\Escritorio\scs_v1.2\venv\Lib\site-packages\django\db\models\query.py", line 1710, in distinct
    raise TypeError(
        "Cannot create distinct fields once a slice has been taken."
    )
TypeError: Cannot create distinct fields once a slice has been taken.
INFO 2025-01-02 15:07:19,940 autoreload 10628 19372 C:\Users\tensa\OneDrive\Escritorio\scs_v1.2\erp_scs\rrhh\views.py changed, reloading.
INFO 2025-01-02 15:07:21,309 autoreload 6408 6048 Watching for file changes with StatReloader
ERROR 2025-01-02 15:07:28,421 log 6408 10300 Internal Server Error: /rrhh/produccion/trabajadores/
Traceback (most recent call last):
  File "C:\Users\tensa\OneDrive\Escritorio\scs_v1.2\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\tensa\OneDrive\Escritorio\scs_v1.2\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\tensa\OneDrive\Escritorio\scs_v1.2\venv\Lib\site-packages\django\views\generic\base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
           ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\tensa\OneDrive\Escritorio\scs_v1.2\venv\Lib\site-packages\django\contrib\auth\mixins.py", line 73, in dispatch
    return super().dispatch(request, *args, **kwargs)
           ~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\tensa\OneDrive\Escritorio\scs_v1.2\venv\Lib\site-packages\django\contrib\auth\mixins.py", line 109, in dispatch
    return super().dispatch(request, *args, **kwargs)
           ~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\tensa\OneDrive\Escritorio\scs_v1.2\venv\Lib\site-packages\django\views\generic\base.py", line 143, in dispatch
    return handler(request, *args, **kwargs)
  File "C:\Users\tensa\OneDrive\Escritorio\scs_v1.2\venv\Lib\site-packages\django\views\generic\list.py", line 174, in get
    context = self.get_context_data()
  File "C:\Users\tensa\OneDrive\Escritorio\scs_v1.2\erp_scs\rrhh\views.py", line 441, in get_context_data
    if context['producciones']:
       ~~~~~~~^^^^^^^^^^^^^^^^
  File "C:\Users\tensa\OneDrive\Escritorio\scs_v1.2\venv\Lib\site-packages\django\db\models\query.py", line 414, in __bool__
    self._fetch_all()
    ~~~~~~~~~~~~~~~^^
  File "C:\Users\tensa\OneDrive\Escritorio\scs_v1.2\venv\Lib\site-packages\django\db\models\query.py", line 1928, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
                         ~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\tensa\OneDrive\Escritorio\scs_v1.2\venv\Lib\site-packages\django\db\models\query.py", line 91, in __iter__
    results = compiler.execute_sql(
        chunked_fetch=self.chunked_fetch, chunk_size=self.chunk_size
    )
  File "C:\Users\tensa\OneDrive\Escritorio\scs_v1.2\venv\Lib\site-packages\django\db\models\sql\compiler.py", line 1561, in execute_sql
    sql, params = self.as_sql()
                  ~~~~~~~~~~~^^
  File "C:\Users\tensa\OneDrive\Escritorio\scs_v1.2\venv\Lib\site-packages\django\db\models\sql\compiler.py", line 747, in as_sql
    extra_select, order_by, group_by = self.pre_sql_setup(
                                       ~~~~~~~~~~~~~~~~~~^
        with_col_aliases=with_col_aliases or bool(combinator),
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "C:\Users\tensa\OneDrive\Escritorio\scs_v1.2\venv\Lib\site-packages\django\db\models\sql\compiler.py", line 84, in pre_sql_setup
    self.setup_query(with_col_aliases=with_col_aliases)
    ~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\tensa\OneDrive\Escritorio\scs_v1.2\venv\Lib\site-packages\django\db\models\sql\compiler.py", line 73, in setup_query
    self.select, self.klass_info, self.annotation_col_map = self.get_select(
                                                            ~~~~~~~~~~~~~~~^
        with_col_aliases=with_col_aliases,
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "C:\Users\tensa\OneDrive\Escritorio\scs_v1.2\venv\Lib\site-packages\django\db\models\sql\compiler.py", line 279, in get_select
    related_klass_infos = self.get_related_selections(select, select_mask)
  File "C:\Users\tensa\OneDrive\Escritorio\scs_v1.2\venv\Lib\site-packages\django\db\models\sql\compiler.py", line 1248, in get_related_selections
    next_klass_infos = self.get_related_selections(
        select,
    ...<5 lines>...
        restricted,
    )
  File "C:\Users\tensa\OneDrive\Escritorio\scs_v1.2\venv\Lib\site-packages\django\db\models\sql\compiler.py", line 1379, in get_related_selections
    raise FieldError(
    ...<6 lines>...
    )
django.core.exceptions.FieldError: Invalid field name(s) given in select_related: 'usuario'. Choices are: perfil_trabajador
INFO 2025-01-02 15:09:48,128 autoreload 6408 6048 C:\Users\tensa\OneDrive\Escritorio\scs_v1.2\erp_scs\rrhh\views.py changed, reloading.
INFO 2025-01-02 15:09:49,539 autoreload 16232 16932 Watching for file changes with StatReloader
ERROR 2025-01-02 15:36:47,710 log 16232 8896 Internal Server Error: /rrhh/liquidaciones/
Traceback (most recent call last):
  File "C:\Users\tensa\OneDrive\Escritorio\scs_v1.2\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\tensa\OneDrive\Escritorio\scs_v1.2\venv\Lib\site-packages\django\core\handlers\base.py", line 220, in _get_response
    response = response.render()
  File "C:\Users\tensa\OneDrive\Escritorio\scs_v1.2\venv\Lib\site-packages\django\template\response.py", line 114, in render
    self.content = self.rendered_content
                   ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\tensa\OneDrive\Escritorio\scs_v1.2\venv\Lib\site-packages\django\template\response.py", line 90, in rendered_content
    template = self.resolve_template(self.template_name)
  File "C:\Users\tensa\OneDrive\Escritorio\scs_v1.2\venv\Lib\site-packages\django\template\response.py", line 72, in resolve_template
    return select_template(template, using=self.using)
  File "C:\Users\tensa\OneDrive\Escritorio\scs_v1.2\venv\Lib\site-packages\django\template\loader.py", line 47, in select_template
    raise TemplateDoesNotExist(", ".join(template_name_list), chain=chain)
django.template.exceptions.TemplateDoesNotExist: rrhh/liquidacion_list.html
WARNING 2025-01-02 15:38:01,511 log 16232 16512 Not Found: /accounts/login/
ERROR 2025-01-02 16:10:01,206 log 16232 22484 Internal Server Error: /rrhh/liquidaciones/crear/
Traceback (most recent call last):
  File "C:\Users\tensa\OneDrive\Escritorio\scs_v1.2\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\tensa\OneDrive\Escritorio\scs_v1.2\venv\Lib\site-packages\django\core\handlers\base.py", line 220, in _get_response
    response = response.render()
  File "C:\Users\tensa\OneDrive\Escritorio\scs_v1.2\venv\Lib\site-packages\django\template\response.py", line 114, in render
    self.content = self.rendered_content
                   ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\tensa\OneDrive\Escritorio\scs_v1.2\venv\Lib\site-packages\django\template\response.py", line 90, in rendered_content
    template = self.resolve_template(self.template_name)
  File "C:\Users\tensa\OneDrive\Escritorio\scs_v1.2\venv\Lib\site-packages\django\template\response.py", line 72, in resolve_template
    return select_template(template, using=self.using)
  File "C:\Users\tensa\OneDrive\Escritorio\scs_v1.2\venv\Lib\site-packages\django\template\loader.py", line 47, in select_template
    raise TemplateDoesNotExist(", ".join(template_name_list), chain=chain)
django.template.exceptions.TemplateDoesNotExist: rrhh/liquidacion_form.html
INFO 2025-01-02 16:11:04,584 autoreload 16232 16932 C:\Users\tensa\OneDrive\Escritorio\scs_v1.2\erp_scs\rrhh\views.py changed, reloading.
INFO 2025-01-02 16:11:06,317 autoreload 1576 22900 Watching for file changes with StatReloader
INFO 2025-01-02 18:49:09,171 autoreload 15008 17548 Watching for file changes with StatReloader
WARNING 2025-01-02 18:49:18,141 log 15008 11816 Not Found: /favicon.ico
WARNING 2025-01-02 18:52:54,659 log 15008 22448 Forbidden (CSRF token from POST incorrect.): /
INFO 2025-01-04 16:53:21,670 autoreload 14512 7236 Watching for file changes with StatReloader
INFO 2025-01-04 17:05:12,836 autoreload 420 18480 Watching for file changes with StatReloader
ERROR 2025-01-04 17:16:29,333 log 420 10012 Internal Server Error: /dashboard/
Traceback (most recent call last):
  File "C:\Python311\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python311\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Programacion\aaaProyectos\Angel\SCSADMIN.CL\erp_scs\dashboard\views.py", line 59, in dashboard_view
    return render(request, 'dashboard.html', context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python311\Lib\site-packages\django\shortcuts.py", line 25, in render
    content = loader.render_to_string(template_name, context, request, using=using)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python311\Lib\site-packages\django\template\loader.py", line 62, in render_to_string
    return template.render(context, request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python311\Lib\site-packages\django\template\backends\django.py", line 107, in render
    return self.template.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python311\Lib\site-packages\django\template\base.py", line 171, in render
    return self._render(context)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python311\Lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python311\Lib\site-packages\django\template\base.py", line 1008, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python311\Lib\site-packages\django\template\base.py", line 1008, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python311\Lib\site-packages\django\template\base.py", line 969, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Python311\Lib\site-packages\django\template\loader_tags.py", line 159, in render
    return compiled_parent._render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python311\Lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python311\Lib\site-packages\django\template\base.py", line 1008, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python311\Lib\site-packages\django\template\base.py", line 1008, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python311\Lib\site-packages\django\template\base.py", line 969, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Python311\Lib\site-packages\django\template\defaulttags.py", line 327, in render
    return nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python311\Lib\site-packages\django\template\base.py", line 1008, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python311\Lib\site-packages\django\template\base.py", line 1008, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python311\Lib\site-packages\django\template\base.py", line 969, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Python311\Lib\site-packages\django\template\defaulttags.py", line 243, in render
    nodelist.append(node.render_annotated(context))
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python311\Lib\site-packages\django\template\base.py", line 969, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Python311\Lib\site-packages\django\template\defaulttags.py", line 480, in render
    url = reverse(view_name, args=args, kwargs=kwargs, current_app=current_app)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python311\Lib\site-packages\django\urls\base.py", line 88, in reverse
    return resolver._reverse_with_prefix(view, prefix, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python311\Lib\site-packages\django\urls\resolvers.py", line 831, in _reverse_with_prefix
    raise NoReverseMatch(msg)
django.urls.exceptions.NoReverseMatch: Reverse for '' not found. '' is not a valid view function or pattern name.
INFO 2025-01-04 18:04:13,420 autoreload 6012 15792 Watching for file changes with StatReloader
WARNING 2025-01-04 18:17:33,055 log 6012 6016 Not Found: /base
